from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("sophios")
except PackageNotFoundError:
    __version__ = "unknown"

# Well, not THIS file.
auto_gen_header = f"""# This file was autogenerated using the Workflow Inference Compiler, version {__version__}
# https://github.com/PolusAI/sophios\n"""
