import importlib
import warnings

# The version this copy of Sophios was built as. setuptools-scm writes _version.py beside
# this file whenever the package is built or installed, so it describes the files that are
# running. Installed metadata would describe whichever `sophios` distribution the
# environment names, which is not this code when it runs from another checkout.
try:
    __version__: str = str(importlib.import_module(f'{__name__}._version').__version__)
except ModuleNotFoundError as error:
    if error.name != f'{__name__}._version':
        raise
    warnings.warn(
        "this copy of sophios was never built, so __version__ is 'unknown'. Run: pip install -e .",
        RuntimeWarning,
    )
    __version__ = 'unknown'

# Well, not THIS file.
auto_gen_header = f"""# This file was autogenerated using Sophios, version {__version__}
# https://github.com/PolusAI/sophios\n"""
