from importlib.metadata import PackageNotFoundError, version
import warnings


def _resolve_version() -> str:
    try:
        return version("sophios")
    except PackageNotFoundError:
        warnings.warn(
            "sophios is not installed; __version__ will be 'unknown'. Run: pip install -e .",
            RuntimeWarning,
            stacklevel=2,
        )
        return "unknown"


__version__ = _resolve_version()

# Well, not THIS file.
auto_gen_header = f"""# This file was autogenerated using the Workflow Inference Compiler, version {__version__}
# https://github.com/PolusAI/sophios\n"""
