import argparse
import sys
from pathlib import Path

from . import __version__
from .wic_types import CompilerOptions, GraphSettings, YamlTagPaths

parser = argparse.ArgumentParser(prog='main', description='Convert a high-level yaml workflow file to CWL.')

# Not `required=`: whether `--yaml` is needed depends on whether one of the
# generate modes was asked for, and argparse cannot express that. The old
# spelling computed it at *import* time from the host process's `sys.argv`, so
# importing sophios from a program whose own command line happened to carry
# `--generate_config` silently made `--yaml` optional. That is the defect this
# module was cleaned up to remove, in the one place a scan for writes to
# `sys.argv` cannot see, because it is a read. `_main` enforces it instead,
# where both generate flags are already parsed and known.
parser.add_argument('--yaml', type=str, default='',
                    help='Yaml workflow file')
group_gen = parser.add_mutually_exclusive_group()
group_gen.add_argument('--generate_schemas', default=False, action="store_true",
                       help='Generate schemas for the files in config.json (search_paths_wic and search_paths_cwl)')
group_gen.add_argument('--generate_config', default=False, action="store_true",
                       help='''Generate default config in wic/global_config.json
                       with default search_paths_wic and search_paths_cwl''')
parser.add_argument('--inputs_file', type=str, required=False, default='',
                    help='Additional inputs Yaml file')
parser.add_argument('--config_file', type=str, required=False, default=str(Path().home()/'wic'/'global_config.json'),
                    help='User provided (JSON) config file')
# version action exits the parser
# Ref : https://github.com/python/cpython/blob/1f515e8a109204f7399d85b7fd806135166422d9/Lib/argparse.py#L1167
parser.add_argument('--version', action='version', version=__version__,
                    default='==SUPPRESS==', help='Current version of the Sophios Compiler')
parser.add_argument('--homedir', type=str, required=False, default=str(Path().home()),
                    help='''The users home directory.
                    This is necessary because CWL clears environment variables (e.g. HOME)''')
parser.add_argument('--pull_dir', type=str, required=False, default=str(Path().cwd()),
                    help='''The user specified pull directory for (singularity) image pull.
                    The default is the current working directory i.e. `pwd`''')
parser.add_argument('--insert_steps_automatically', default=False, action="store_true",
                    help='''Attempt to fix inference failures by speculatively
                    inserting workflow steps from a curated whitelist.''')
parser.add_argument('--no_provenance', default=False, action="store_true",
                    help='''Do not use the --provenance feature of CWL.
                    (You should only disable provenance if absolutely necessary.)''')
parser.add_argument('--copy_output_files', default=False, action="store_true",
                    help='Copy primary outputs into the legacy outdir/ layout after a successful cwltool run.')
parser.add_argument('--cwl_inline_runtag', default=False, action="store_true",
                    help='Copies cwl adapter file contents inline into the final .cwl in autogenerated/')

parser.add_argument('--parallel', default=False, action="store_true",
                    help='''When running locally, execute independent steps in parallel.
                    \nThis is required for real-time analysis, but it may cause issues with
                    \nhanging (particularly when scattering). See user guide for details.''')
parser.add_argument('--quiet', default=False, action="store_true",
                    help='''Disable verbose output. This will not print out the commands used for each step,
                    and it will capture all stdout/stderr into log files for each step.''')
parser.add_argument('--cwl_runner', type=str, required=False, default='cwltool', choices=['cwltool', 'toil-cwl-runner'],
                    help='The CWL runner to use for running workflows locally.')
parser.add_argument('--allow_raw_cwl', default=False, action="store_true",
                    help='Do not check whether the input to a workflow step refers to the workflow inputs: tag')
parser.add_argument('--ignore_docker_install', default=False, action="store_true",
                    help='''Do not check whether docker is installed before running workflows.
                    \n--ignore_docker_install does NOT change whether or not any step in your workflow uses docker!''')
parser.add_argument('--ignore_docker_processes', default=False, action="store_true",
                    help='Do not check whether there are too many running docker processes before running workflows.')
parser.add_argument('--container_engine', default='docker',
                    help='Specify which command to use to run OCI containers.')

parser.add_argument('--docker_remove_entrypoints', default=False, action="store_true",
                    help='''Remove entrypoints from docker images before running workflows.
                    See https://cwl.discourse.group/t/override-docker-entrypoint-in-command-line-tool/695/2
                    If your CWL CommandLineTools rely on non-portable docker entrypoints
                    (i.e. if they do NOT explicitly have baseCommand: and/or arguments: tags)
                    then this flag will almost certainly cause your workflows to fail.
                    In other words, this flag can be used to tell you if your workflows are
                    trapped inside a walled garden of docker containers or if there is at least a chance that
                    they can be run in dev environments (conda, etc) and/or directly on the host machine.''')

parser.add_argument('--partial_failure_enable', default=False, action="store_true",
                    help='''Let workflows to continue with partial failures
                    \n(i.e. run next steps after failure step by guarding for possible no input)''')

parser.add_argument('--partial_failure_success_codes', nargs='*', type=int, default=[0, 1], required=False,
                    help='Let users add custom error codes to be treated as success')

parser.add_argument('--partial_failure_success_codes_range', nargs=2, type=int, default=[0, 1], required=False,
                    help='Let users add custom error code range to be treated as success')

group_run = parser.add_mutually_exclusive_group()
group_run.add_argument('--generate_run_script', default=False, action="store_true",
                       help='Just generates run.sh and exits. Does not actually invoke ./run.sh')
group_run.add_argument('--run_local', default=False, action="store_true",
                       help='After generating the cwl file(s), run it on your local machine.')
group_run.add_argument('--generate_cwl_workflow', required=False, default=False, action="store_true",
                       help='Compile the workflow without pulling the docker image')
parser.add_argument('--cwl_inline_subworkflows', default=False, action="store_true",
                    help='Before generating the cwl file, inline all subworkflows.')
parser.add_argument('--write_intermediate_wic', default=False, action="store_true",
                    help='Write intermediate compiler .wic trees under autogenerated/ for debugging.')
parser.add_argument('--inference_disable', default=False, action="store_true",
                    help='Disables use of the inference algorithm when compiling.')
parser.add_argument('--inference_use_naming_conventions', default=False, action="store_true",
                    help='Enables the use of naming conventions in the inference algorithm')
parser.add_argument('--validate_plugins', default=False, action="store_true",
                    help='Validate all CWL CommandLineTools')
parser.add_argument('--ignore_validation_errors', default=False, action="store_true",
                    help='Temporarily ignore validation errors. Do not use this permanently!')
parser.add_argument('--no_skip_dollar_schemas', default=False, action="store_true",
                    help='''Does not skip processing $schemas tags in CWL files for performance.
                    Skipping significantly improves initial validation performance, but is not always desired.
                    See https://github.com/common-workflow-language/cwltool/issues/623''')
parser.add_argument('--cachedir', type=str, required=False, default='cachedir',
                    help='The directory to save intermediate results; useful with RealtimePlots.py')
parser.add_argument('--outdir', type=str, required=False, default='',
                    help='Workflow output directory passed to the CWL runner.')

parser.add_argument('--graphviz', default=False, action="store_true",
                    help='Generate a DAG using graphviz.')
parser.add_argument('--graph_label_edges', default=False, action="store_true",
                    help='Label the graph edges with the name of the intermediate input/output.')
parser.add_argument('--graph_label_stepname', default=False, action="store_true",
                    help='Prepend the step name to each step node.')
parser.add_argument('--graph_show_inputs', default=False, action="store_true",
                    help='Add nodes to the graph representing the workflow inputs.')
parser.add_argument('--graph_show_outputs', default=False, action="store_true",
                    help='Add nodes to the graph representing the workflow outputs.')
parser.add_argument('--graph_inline_depth', type=int, required=False, default=sys.maxsize,
                    help='Controls the depth of subgraphs which are displayed.')
parser.add_argument('--graph_dark_theme', default=False, action="store_true",
                    help='Changees the color of the fonts and edges from white to black.')
parser.add_argument('--custom_net', type=str, required=False,
                    help='Passes --custom-net flag to cwltool.')
parser.add_argument('--passthrough_flags', type=str, default='no', required=False,
                    help='''Indicates that the user is passing flags to the cwl_runner backend.
                    No checks are done on the flags or values passed.
                    User must verify that they are sending correct flags.
                    only two valid values of this flag 'yes' or 'no'.
                    If set to 'no' (default) passthrough flags won't be sent to the cwl_runner backend.''')


def _argv(yaml_path: str = '', suppliedargs: list[str] | None = None) -> list[str]:
    """The argument list a synthesised parse should read.

    Note there is no program name: `parse_args` takes the arguments *after*
    argv[0]. Passing the list explicitly is the whole point — this module used
    to build a full argv and install it over `sys.argv` with
    `unittest.mock.patch` so that a no-argument `parse_args()` would read it.
    That put a test idiom on the production path and mutated global process
    state to compute a value, in a library other people embed.
    """
    return ['--yaml', yaml_path] + (suppliedargs or [])


def get_args(yaml_path: str = '', suppliedargs: list[str] | None = None) -> argparse.Namespace:
    """This is used to get mock command line arguments, default + suppled args

    Returns:
        argparse.Namespace: The mocked command line arguments
    """
    return parser.parse_args(_argv(yaml_path, suppliedargs))


def get_known_and_unknown_args(
    yaml_path: str = '', suppliedargs: list[str] | None = None
) -> tuple[argparse.Namespace, list[str]]:
    """This is used to get mock command line arguments, default + suppled args

    Returns:
        tuple[argparse.Namespace, list[str]]: The mocked, recognized command line arguments,
            and the list of remaining unrecognized argument strings.
    """
    return parser.parse_known_args(_argv(yaml_path, suppliedargs))


def default_compilation_settings() -> tuple[CompilerOptions, GraphSettings, YamlTagPaths]:
    """The settings a compilation runs with when nobody has chosen otherwise.

    This is what a library caller wants — the Python API, the schema
    generator, the subinterpreter — and it exists so that asking for defaults
    is a thing you can *say*. Previously the only way to obtain them was to
    fabricate a command line, so library code called a CLI helper and got its
    configuration from an argv that no user had typed. Defaults still come
    from one place, the parser's own `default=` values; only the fiction is
    gone.
    """
    return get_dicts_for_compilation(get_args())


def get_dicts_for_compilation(args: argparse.Namespace) -> tuple[CompilerOptions, GraphSettings, YamlTagPaths]:
    """Split parsed command-line arguments into the three dicts compilation needs.

    The adapter at the CLI boundary, and the only function here that takes an
    `argparse.Namespace`. Arguments are parsed once, converted here, and
    passed onward as plain settings — nothing downstream of `main` sees a
    Namespace, and no library signature grows an `args` parameter.

    `args` is required on purpose. It used to default to a fresh parse of a
    synthesised argv, which meant a caller holding the user's real arguments
    could forget to pass them and silently compile with defaults instead —
    which is what `main` did, so `--lang_version`, `--allow_raw_cwl`,
    `--inference_disable`, `--partial_failure_enable`,
    `--insert_steps_automatically` and every graph setting were discarded on
    the way to the compiler. Callers that genuinely want defaults now say so
    with `default_compilation_settings()`.
    """
    # core compiler options for transformation into CWL
    compiler_options: CompilerOptions = {
        'partial_failure_enable': args.partial_failure_enable,
        'inference_use_naming_conventions': args.inference_use_naming_conventions,
        'insert_steps_automatically': args.insert_steps_automatically,
        'inference_disable': args.inference_disable,
        'allow_raw_cwl': args.allow_raw_cwl,
    }

    # to be given to graph util functions
    graph_settings: GraphSettings = {
        'graph_dark_theme': args.graph_dark_theme,
        'graph_inline_depth': args.graph_inline_depth,
        'graph_label_edges': args.graph_label_edges,
        'graph_label_stepname': args.graph_label_stepname,
        'graph_show_outputs': args.graph_show_outputs,
        'graph_show_inputs': args.graph_show_inputs,
    }

    # to be given to io absolute_yaml_tags function
    yaml_tag_paths: YamlTagPaths = {
        'cachedir': args.cachedir,
        'yaml': args.yaml,
        'homedir': args.homedir,
    }
    return (compiler_options, graph_settings, yaml_tag_paths)
