import argparse
import sys
from pathlib import Path
import shutil
import subprocess as sub
import traceback
import json

import graphviz
import networkx as nx

from sophios.lang import wic_schema
from sophios.lang.diagnostics import SophiosError
from sophios.ir.artifacts import CompilationResult
from . import input_output as io
from . import post_compile as pc
from . import cli, compiler, plugins, run_local
from .ir import frontdoor
from .ir.frontdoor import SourceBundle
from .wic_types import (CompilerOptions, GraphData, GraphReps, GraphSettings, Json,
                        Tools, YamlTagPaths)

#: Where `--generate_schemas` writes, relative to the working directory, and
#: where editors are pointed at it (see `.vscode/settings.json`).
SCHEMA_PATH = Path('autogenerated/schemas/wic.json')


def _write_schema(path: Path) -> None:
    """Write the language's JSON Schema, generated from the AST, for editors.

    Syntax only, so it is the same on every machine: which steps exist here and
    which ports they declare are for Resolve and Lower to report, with
    positions, not for a schema to enumerate.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(wic_schema(), indent=2), encoding='utf-8')


def _load_source_bundle(args: argparse.Namespace,
                        yml_paths: dict[str, dict[str, Path]],
                        tools_cwl: Tools) -> tuple[str, str, SourceBundle]:
    """Read and parse the root workflow and everything it reaches.

    Nothing is spliced into anything and nothing is rebuilt, so the document
    the compiler reads is the one on disk and a diagnostic's position is a
    place the reader can open.
    """
    yaml_path = args.yaml
    yaml_stem = Path(yaml_path).stem
    Path('autogenerated/').mkdir(parents=True, exist_ok=True)
    bundle = frontdoor.bundle_from_disk(Path(yaml_path), yml_paths, tools_cwl)
    return yaml_path, yaml_stem, bundle


def _compile_loaded_document(yaml_path: str, yaml_stem: str, bundle: SourceBundle, tools_cwl: Tools,
                             compiler_options: CompilerOptions, graph_settings: GraphSettings,
                             yaml_tag_paths: YamlTagPaths) -> tuple[graphviz.Digraph, CompilationResult]:
    """Build the root graph view and compile to a graph-derived result."""
    rootgraph = graphviz.Digraph(name=yaml_path)
    # newrank='True' ranks nodes globally (rather than per-cluster), which is
    # required for GraphData.ranksame constraints to work across subgraphs/clusters.
    rootgraph.attr(newrank='True')
    rootgraph.attr(bgcolor="transparent")  # Useful for making slides
    font_edge_color = 'black' if graph_settings['graph_dark_theme'] else 'white'
    rootgraph.attr(fontcolor=font_edge_color)

    # This can be used to visually 'inline' all subworkflows (but NOT the CWL).
    # rootgraph.attr(style='invis')
    # Note that since invisible objects still affect the graphviz layout (by design),
    # this can be used to control the layout of the individual nodes, even if
    # you don't necessarily want subworkflows.

    # rootgraph.attr(rankdir='LR') # When --graph_inline_depth 1, this usually looks better.
    with rootgraph.subgraph(name=f'cluster_{yaml_path}') as subgraph_gv:
        # get the label (if any) from the workflow
        # The root's own `wic: graphviz:` label, read from the document that
        # is compiled.
        root = bundle.parsed.document
        drawn = dict(root.sidecar.entries).get('graphviz') if root and root.sidecar else None
        label = drawn.get('label', yaml_path) if isinstance(drawn, dict) else yaml_path
        subgraph_gv.attr(label=label)
        subgraph_gv.attr(color='lightblue')  # color of cluster subgraph outline
        subgraph_nx = nx.DiGraph()
        graphdata = GraphData(yaml_path)
        subgraph = GraphReps(subgraph_gv, subgraph_nx, graphdata)

        try:
            result = compiler.compile_source(
                bundle, compiler_options, graph_settings, yaml_tag_paths,
                relative_run_path=True, testing=False, graph_target=subgraph)
        except SophiosError as e:
            # The library reports; only this adapter is allowed to exit. The
            # messages are the same ones the old exit sites printed — but the
            # banner has to stay: this arm intercepts failures that used to
            # reach the handler below, and a message naming neither the
            # workflow nor the file is a worse error than the one it replaced.
            # No traceback file, though: a reported failure is not a crash,
            # and error_<stem>.txt exists to hide stack traces users cannot
            # act on.
            print('Failed to compile', yaml_path)
            for diagnostic in e.diagnostics:
                print(diagnostic.message)
            sys.exit(1)
        except Exception as e:
            # Certain constraints are conditionally dependent on values and are
            # not easily encoded in the schema, so catch them here.
            # Moreover, although we check for the existence of input files in
            # stage_input_files, we cannot encode file existence in json schema
            # to check the python_script script: tag before compile time.
            print('Failed to compile', yaml_path)
            print(f'See error_{yaml_stem}.txt for detailed technical information.')
            # Do not display a nasty stack trace to the user; hide it in a file.
            with open(f'error_{yaml_stem}.txt', mode='w', encoding='utf-8') as f:
                # https://mypy.readthedocs.io/en/stable/common_issues.html#python-version-and-system-platform-checks
                traceback.print_exception(type(e), value=e, tb=None, file=f)
            sys.exit(1)
        # The resolved language version is reported on every compile, not
        # only on failure — nobody should have to guess which language their
        # file was read as.
        print('Sophios lang_version:', result.lang_version)
    return rootgraph, result


def main() -> None:
    """CLI entry point: run, and convert reported failures to exit codes."""
    try:
        _main()
    except SophiosError as e:
        for diagnostic in e.diagnostics:
            print(diagnostic.message)
        sys.exit(1)


def _main() -> None:
    """See docs/userguide.md"""
    args, unknown_args = cli.parser.parse_known_args()
    plugins.logging_filters()

    # `--yaml` is required unless one of the generate modes was asked for.
    # Checked here rather than by argparse: the requirement is conditional on
    # another flag, which argparse cannot express without reading `sys.argv`
    # at import time — see the note in cli.py.
    if not args.yaml and not (args.generate_config or args.generate_schemas):
        cli.parser.error('the following arguments are required: --yaml')
    if args.ignore_validation_errors:
        print('Warning: --ignore_validation_errors is deprecated and does nothing; '
              'nothing validates a file against a schema any more.', file=sys.stderr)

    if args.generate_config:
        default_config_file = io.default_config_file(Path(args.homedir))
        if default_config_file.exists():
            print(f'Config already exists. To overwrite delete {default_config_file.parent} directory. Exiting')
        else:
            io.generate_config(default_config_file)
            print('Finished generating config. Exiting.')
        sys.exit(0)
    if args.generate_schemas:
        _write_schema(SCHEMA_PATH)
        print('Finished generating schemas. Exiting.')
        sys.exit(0)
    global_config: Json = io.get_config(args.config_file, Path(args.homedir))

    tools_cwl = plugins.get_tools_cwl(global_config, args.validate_plugins, args.quiet)
    # pass around config object instead of reading from the disk!
    yml_paths = plugins.get_yml_paths(global_config)

    yaml_path, yaml_stem, bundle = _load_source_bundle(args, yml_paths, tools_cwl)

    # The one conversion from parsed arguments to settings, at the boundary.
    # Everything below this line takes values; no Namespace goes further.
    compiler_options, graph_settings, yaml_tag_paths = cli.get_dicts_for_compilation(args)
    compiler_options['inference_rules'] = global_config.get('inference_rules', {})
    compiler_options['renaming_conventions'] = global_config.get('renaming_conventions', [])
    rootgraph, compilation = _compile_loaded_document(
        yaml_path, yaml_stem, bundle, tools_cwl,
        compiler_options, graph_settings, yaml_tag_paths)
    artifact = compilation.artifact

    artifact = plugins.cwl_prepend_dockerFile_include_path_artifact(artifact)

    if args.partial_failure_enable:
        artifact = plugins.cwl_update_outputs_optional_artifact(
            artifact, args.partial_failure_success_codes_range,
            args.partial_failure_success_codes)

    # Source flattening used to reimplement workflow-call semantics before the
    # compiler could judge them. Both public flags now embed the already-linked
    # child graph, so Link remains the sole owner of call bindings and outputs.
    if args.cwl_inline_runtag or args.cwl_inline_subworkflows:
        artifact = pc.inline_artifact_runs(artifact)

    if args.graphviz:
        if shutil.which('dot'):
            # Render the GraphViz diagram
            rootgraph.save(f'autogenerated/{yaml_stem}.wic.gv')
            cmdline = f'cat autogenerated/{yaml_stem}.wic.gv | dot -Tpng > autogenerated/{yaml_stem}.wic.gv.png'
            sub.run(cmdline, shell=True, capture_output=False, check=False)
            # Use the explicit code above because the .render() method saves
            # the png file in the same directory as the original yaml_path
            # rootgraph.render(format='png')  # Default pdf. See https://graphviz.org/docs/outputs/

            # For comparison, the built-in cwltool graphiz support generates a visual abomination:
            cmdline = f'cwltool_filterlog --print-dot autogenerated/{yaml_stem}.cwl ' \
                f'| dot -Tsvg > autogenerated/{yaml_stem}.svg'
            sub.run(cmdline, shell=True, capture_output=True, check=False)
        else:
            print("Warning: Cannot generate graphviz diagrams because the `dot` executable was not found.")
            print("(This may happen if you installed the graphviz python package")
            print("but not the graphviz system package.)")

    if args.run_local or args.generate_run_script:
        # verify container_engine install and config
        pc.verify_container_engine_config(args.container_engine, args.ignore_docker_install,
                                          ignore_container_processes=args.ignore_docker_processes)
        # Only now we need to write the final cwl for docker-extract
        # and then for actually running using a cwl_runner
        basepath = 'autogenerated'
        io.write_artifacts_to_disk(artifact, Path(basepath), True, args.inputs_file)
        # extract the container images
        pc.cwl_docker_extract(args.container_engine, args.pull_dir, Path(basepath) / f'{yaml_stem}.cwl')
        if args.docker_remove_entrypoints:
            artifact = pc.remove_artifact_entrypoints(args.container_engine, artifact)
        # stage input files for run
        pc.stage_input_files(artifact.job_inputs, Path(args.yaml).parent.absolute(), basepath)
        # No need to re-write to disk as nothing of the cwl or yaml_inputs has changed!
        # if there are no unknown_args then unkown_args will be an empty list []
        # so no need for a separate check of a particular flag!
        # Now build the dict, instead of passing args to run_local
        run_args_dict = {}
        run_args_dict['container_engine'] = args.container_engine
        run_args_dict['cwl_runner'] = args.cwl_runner
        run_args_dict['copy_output_files'] = 'yes' if args.copy_output_files else 'no'
        run_args_dict['cachedir'] = args.cachedir
        run_args_dict['outdir'] = args.outdir
        run_args_dict['generate_run_script'] = 'yes' if args.generate_run_script else 'no'
        run_local.run_local(run_args_dict, False,
                            workflow_name=artifact.name, passthrough_args=unknown_args, basepath=basepath,
                            output_directories=run_local.output_directories(compilation.graph))

    elif args.generate_cwl_workflow:
        io.write_artifacts_to_disk(artifact, Path('autogenerated/'), True, args.inputs_file)
    else:
        print('Please specify either --generate_cwl_workflow (compile) or --run_local (run)')
        sys.exit(1)


if __name__ == '__main__':
    main()
