import argparse
import sys
from pathlib import Path
import shutil
import subprocess as sub
import traceback
import json

import graphviz
import networkx as nx
import yaml
from jsonschema import Draft202012Validator

from sophios.lang.diagnostics import SophiosError
from sophios.lang.error_codes import SophiosErrorCode
from sophios.ir.artifacts import CompilationResult
from sophios.utils_yaml import wic_loader
from . import input_output as io
from . import post_compile as pc
from . import cli, compiler, plugins, run_local, utils  # , utils_graphs
from .ir import frontdoor
from .ir.frontdoor import SourceBundle
from .schemas import wic_schema
from .wic_types import (CompilerOptions, GraphData, GraphReps, GraphSettings, Json,
                        StepId, Tools, Yaml, YamlTagPaths, YamlTree)


def _write_intermediate_source(yaml_stem: str, source: str, *, enabled: bool) -> Path | None:
    """Write the source the compiler read, only when explicitly enabled."""
    if not enabled:
        return None
    output_path = Path('autogenerated') / f'{yaml_stem}_source.wic'
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(source, encoding='utf-8')
    return output_path


def _load_source_bundle(args: argparse.Namespace,
                        yml_paths: dict[str, dict[str, Path]],
                        tools_cwl: Tools) -> tuple[str, str, SourceBundle]:
    """Read the root workflow and everything it reaches, as text.

    Nothing is spliced into anything and nothing is rebuilt, so the document
    the compiler parses is the one on disk and a diagnostic's position is a
    place the reader can open.
    """
    yaml_path = args.yaml
    yaml_stem = Path(yaml_path).stem
    Path('autogenerated/').mkdir(parents=True, exist_ok=True)
    bundle = frontdoor.bundle_from_disk(Path(yaml_path), yml_paths, tools_cwl)
    # What the compiler read, rather than a tree it built: the three trees this
    # used to dump were stages of an assembly that no longer happens.
    _write_intermediate_source(yaml_stem, bundle.source, enabled=args.write_intermediate_wic)
    return yaml_path, yaml_stem, bundle


def _compile_loaded_document(yaml_path: str, yaml_stem: str, bundle: SourceBundle, tools_cwl: Tools,
                             compiler_options: CompilerOptions, graph_settings: GraphSettings,
                             yaml_tag_paths: YamlTagPaths) -> tuple[graphviz.Digraph, CompilationResult]:
    """Build the root graph view and compile to a graph-derived result."""
    rootgraph = graphviz.Digraph(name=yaml_path)
    # newrank='True' ranks nodes globally (rather than per-cluster), which is
    # required for GraphData.ranksame constraints to work across subgraphs/clusters.
    rootgraph.attr(newrank='True')
    rootgraph.attr(bgcolor="transparent")  # Useful for making slides
    font_edge_color = 'black' if graph_settings['graph_dark_theme'] else 'white'
    rootgraph.attr(fontcolor=font_edge_color)

    # This can be used to visually 'inline' all subworkflows (but NOT the CWL).
    # rootgraph.attr(style='invis')
    # Note that since invisible objects still affect the graphviz layout (by design),
    # this can be used to control the layout of the individual nodes, even if
    # you don't necessarily want subworkflows.

    # rootgraph.attr(rankdir='LR') # When --graph_inline_depth 1, this usually looks better.
    with rootgraph.subgraph(name=f'cluster_{yaml_path}') as subgraph_gv:
        # get the label (if any) from the workflow
        # The root's own `wic: graphviz:` label, read from the text that was
        # compiled -- not from an assembled tree, which no longer exists.
        root_wic = (yaml.load(bundle.source, Loader=wic_loader()) or {}).get('wic') or {}
        step_i_wic_graphviz = root_wic.get('graphviz', {})
        label = step_i_wic_graphviz.get('label', yaml_path)
        subgraph_gv.attr(label=label)
        subgraph_gv.attr(color='lightblue')  # color of cluster subgraph outline
        subgraph_nx = nx.DiGraph()
        graphdata = GraphData(yaml_path)
        subgraph = GraphReps(subgraph_gv, subgraph_nx, graphdata)

        try:
            result = compiler.compile_source(
                bundle, compiler_options, graph_settings, yaml_tag_paths,
                relative_run_path=True, testing=False, graph_target=subgraph)
        except SophiosError as e:
            # The library reports; only this adapter is allowed to exit. The
            # messages are the same ones the old exit sites printed — but the
            # banner has to stay: this arm intercepts failures that used to
            # reach the handler below, and a message naming neither the
            # workflow nor the file is a worse error than the one it replaced.
            # No traceback file, though: a reported failure is not a crash,
            # and error_<stem>.txt exists to hide stack traces users cannot
            # act on.
            print('Failed to compile', yaml_path)
            for diagnostic in e.diagnostics:
                print(diagnostic.message)
            sys.exit(1)
        except Exception as e:
            # Certain constraints are conditionally dependent on values and are
            # not easily encoded in the schema, so catch them here.
            # Moreover, although we check for the existence of input files in
            # stage_input_files, we cannot encode file existence in json schema
            # to check the python_script script: tag before compile time.
            print('Failed to compile', yaml_path)
            print(f'See error_{yaml_stem}.txt for detailed technical information.')
            # Do not display a nasty stack trace to the user; hide it in a file.
            with open(f'error_{yaml_stem}.txt', mode='w', encoding='utf-8') as f:
                # https://mypy.readthedocs.io/en/stable/common_issues.html#python-version-and-system-platform-checks
                traceback.print_exception(type(e), value=e, tb=None, file=f)
            sys.exit(1)
        # The resolved language version is reported on every compile, not
        # only on failure — nobody should have to guess which language their
        # file was read as.
        print('Sophios lang_version:', result.lang_version)
    return rootgraph, result


def main() -> None:
    """CLI entry point: run, and convert reported failures to exit codes."""
    try:
        _main()
    except SophiosError as e:
        for diagnostic in e.diagnostics:
            print(diagnostic.message)
        sys.exit(1)


def _main() -> None:
    """See docs/userguide.md"""
    args, unknown_args = cli.parser.parse_known_args()
    plugins.logging_filters()

    # `--yaml` is required unless one of the generate modes was asked for.
    # Checked here rather than by argparse: the requirement is conditional on
    # another flag, which argparse cannot express without reading `sys.argv`
    # at import time — see the note in cli.py.
    if not args.yaml and not (args.generate_config or args.generate_schemas):
        cli.parser.error('the following arguments are required: --yaml')

    # User may specify a different homedir
    default_config_file = Path(args.homedir)/'wic'/'global_config.json'
    if args.generate_config:
        if default_config_file.exists():
            print(f'Config already exists. To overwrite delete {default_config_file.parent} directory. Exiting')
        else:
            basic_config = io.get_basic_config()
            io.write_config_to_disk(basic_config, default_config_file)
            io.move_adapters_and_examples(basic_config)
            print('Finished generating config. Exiting.')
        sys.exit(0)
    global_config: Json = io.get_config(Path(args.config_file), default_config_file)

    tools_cwl = plugins.get_tools_cwl(global_config, args.validate_plugins, args.quiet)
    # pass around config object instead of reading from the disk!
    yml_paths = plugins.get_yml_paths(global_config)

    # Generate schemas for validation and vscode IntelliSense code completion
    yaml_stems = utils.flatten([list(p) for p in yml_paths.values()])
    schema_store: dict[str, Json] = {}
    validator = wic_schema.get_validator(tools_cwl, yaml_stems, schema_store, write_to_disk=False)

    # Generating yml schemas every time takes ~20 seconds and guarantees the
    # subworkflow schemas are always up to date. However, since it compiles all
    # wic files, if there are any errors in any of the wic files, the user may
    # be confused by an error message when the --yaml file is correct.
    # For now, require the user to update the schemas manually. In the future,
    # we may use a filewatcher.
    if args.generate_schemas:
        yml_paths_tuples = [(yml_path_str, yml_path)
                            for yml_namespace, yml_paths_dict in yml_paths.items()
                            for yml_path_str, yml_path in yml_paths_dict.items()]

        for yml_path_str, yml_path in yml_paths_tuples:
            try:
                schema = wic_schema.compile_workflow_generate_schema(
                    args.homedir, yml_path_str, yml_path, tools_cwl, yml_paths,
                    validator, args.ignore_validation_errors,
                    args.write_intermediate_wic)
            except SophiosError as exc:
                if exc.diagnostics and all(
                        item.code is SophiosErrorCode.UNDEFINED_EDGE
                        for item in exc.diagnostics):
                    # A fragment whose explicit edge comes from an includer has
                    # no standalone schema. Its permissive placeholder remains;
                    # the composed root is still compiled and checked below.
                    continue
                raise
            # overwrite placeholders in schema_store. See comment in get_validator()
            schema_store[schema['$id']] = schema

        # Now that we compiled all of the subworkflows once with the permissive/weak schema,
        # compile the root yml workflow again with the restrictive/strict schema.
        validator = wic_schema.get_validator(tools_cwl, yaml_stems, schema_store, write_to_disk=True)
        schema_store_path = Path('autogenerated/schemas/schema_store.json')
        schema_store_path.parent.mkdir(parents=True, exist_ok=True)
        with open(schema_store_path, mode='w', encoding='utf-8') as f:
            json.dump(schema_store, f, indent=2)

    if args.generate_schemas:
        print('Finished generating schemas. Exiting.')
        sys.exit(0)

    yaml_path, yaml_stem, bundle = _load_source_bundle(args, yml_paths, tools_cwl)

    # The one conversion from parsed arguments to settings, at the boundary.
    # Everything below this line takes values; no Namespace goes further.
    compiler_options, graph_settings, yaml_tag_paths = cli.get_dicts_for_compilation(args)
    compiler_options['inference_rules'] = global_config.get('inference_rules', {})
    compiler_options['renaming_conventions'] = global_config.get('renaming_conventions', [])
    rootgraph, compilation = _compile_loaded_document(
        yaml_path, yaml_stem, bundle, tools_cwl,
        compiler_options, graph_settings, yaml_tag_paths)
    artifact = compilation.artifact

    artifact = plugins.cwl_prepend_dockerFile_include_path_artifact(artifact)

    if args.partial_failure_enable:
        artifact = plugins.cwl_update_outputs_optional_artifact(
            artifact, args.partial_failure_success_codes_range,
            args.partial_failure_success_codes)

    # Source flattening used to reimplement workflow-call semantics before the
    # compiler could judge them. Both public flags now embed the already-linked
    # child graph, so Link remains the sole owner of call bindings and outputs.
    if args.cwl_inline_runtag or args.cwl_inline_subworkflows:
        artifact = pc.inline_artifact_runs(artifact)

    if args.graphviz:
        if shutil.which('dot'):
            # Render the GraphViz diagram
            rootgraph.save(f'autogenerated/{yaml_stem}.wic.gv')
            cmdline = f'cat autogenerated/{yaml_stem}.wic.gv | dot -Tpng > autogenerated/{yaml_stem}.wic.gv.png'
            sub.run(cmdline, shell=True, capture_output=False, check=False)
            # Use the explicit code above because the .render() method saves
            # the png file in the same directory as the original yaml_path
            # rootgraph.render(format='png')  # Default pdf. See https://graphviz.org/docs/outputs/

            # For comparison, the built-in cwltool graphiz support generates a visual abomination:
            cmdline = f'cwltool_filterlog --print-dot autogenerated/{yaml_stem}.cwl ' \
                f'| dot -Tsvg > autogenerated/{yaml_stem}.svg'
            sub.run(cmdline, shell=True, capture_output=True, check=False)
        else:
            print("Warning: Cannot generate graphviz diagrams because the `dot` executable was not found.")
            print("(This may happen if you installed the graphviz python package")
            print("but not the graphviz system package.)")

    if args.run_local or args.generate_run_script:
        # verify container_engine install and config
        pc.verify_container_engine_config(args.container_engine, args.ignore_docker_install)
        # Only now we need to write the final cwl for docker-extract
        # and then for actually running using a cwl_runner
        basepath = 'autogenerated'
        io.write_artifacts_to_disk(artifact, Path(basepath), True, args.inputs_file)
        # extract the container images
        pc.cwl_docker_extract(args.container_engine, args.pull_dir, Path(basepath) / f'{yaml_stem}.cwl')
        if args.docker_remove_entrypoints:
            artifact = pc.remove_artifact_entrypoints(args.container_engine, artifact)
        # stage input files for run
        pc.stage_input_files(artifact.job_inputs, Path(args.yaml).parent.absolute(), basepath)
        # No need to re-write to disk as nothing of the cwl or yaml_inputs has changed!
        # if there are no unknown_args then unkown_args will be an empty list []
        # so no need for a separate check of a particular flag!
        # Now build the dict, instead of passing args to run_local
        run_args_dict = {}
        run_args_dict['container_engine'] = args.container_engine
        run_args_dict['cwl_runner'] = args.cwl_runner
        run_args_dict['copy_output_files'] = 'yes' if args.copy_output_files else 'no'
        run_args_dict['cachedir'] = args.cachedir
        run_args_dict['outdir'] = args.outdir
        run_args_dict['generate_run_script'] = 'yes' if args.generate_run_script else 'no'
        run_local.run_local(run_args_dict, False,
                            workflow_name=artifact.name, passthrough_args=unknown_args, basepath=basepath)

    elif args.generate_cwl_workflow:
        io.write_artifacts_to_disk(artifact, Path('autogenerated/'), True, args.inputs_file)
    else:
        print('Please specify either --generate_cwl_workflow (compile) or --run_local (run)')
        sys.exit(1)


if __name__ == '__main__':
    main()
