import argparse
import sys
from pathlib import Path
import shutil
import subprocess as sub
import traceback
import json
from dataclasses import replace
from collections.abc import Iterable
from typing import Iterator

import graphviz
import networkx as nx
import yaml

from sophios.lang import wic_schema
from sophios.lang.diagnostics import Diagnostic, SophiosError
from sophios.ir.artifacts import CompilationResult
from . import input_output as io
from . import post_compile as pc
from . import cli, compiler, plugins, realtime, run_local
from .ir import frontdoor
from .ir.frontdoor import SourceBundle
from .wic_types import CompilerOptions, GraphData, GraphReps, GraphSettings, Json, Tools

#: Where `--generate_schemas` writes, relative to the working directory, and
#: where editors are pointed at it (see `.vscode/settings.json`).
SCHEMA_PATH = Path('autogenerated/schemas/wic.json')


def _write_schema(path: Path) -> None:
    """Write the language's JSON Schema, generated from the AST, for editors.

    Syntax only, so it is the same on every machine: which steps exist here and
    which ports they declare are for Resolve and Lower to report, with
    positions, not for a schema to enumerate.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(wic_schema(), indent=2), encoding='utf-8')


def _load_source_bundle(args: argparse.Namespace,
                        yml_paths: dict[str, dict[str, Path]],
                        tools_cwl: Tools) -> tuple[str, str, SourceBundle]:
    """Read and parse the root workflow and everything it reaches.

    Nothing is spliced into anything and nothing is rebuilt, so the document
    the compiler reads is the one on disk and a diagnostic's position is a
    place the reader can open.
    """
    yaml_path = args.yaml
    yaml_stem = Path(yaml_path).stem
    Path('autogenerated/').mkdir(parents=True, exist_ok=True)
    bundle = frontdoor.bundle_from_disk(Path(yaml_path), yml_paths, tools_cwl)
    return yaml_path, yaml_stem, bundle


def _compile_loaded_document(yaml_path: str, yaml_stem: str, bundle: SourceBundle,
                             yml_paths: dict[str, dict[str, Path]], tools_cwl: Tools,
                             compiler_options: CompilerOptions, graph_settings: GraphSettings
                             ) -> tuple[graphviz.Digraph, CompilationResult, tuple[realtime.Analysis, ...]]:
    """Build the root graph view and compile to a graph-derived result, and each real-time analysis it declares."""
    rootgraph = graphviz.Digraph(name=yaml_path)
    # newrank='True' ranks nodes globally (rather than per-cluster), which is
    # required for GraphData.ranksame constraints to work across subgraphs/clusters.
    rootgraph.attr(newrank='True')
    rootgraph.attr(bgcolor="transparent")  # Useful for making slides
    font_edge_color = 'black' if graph_settings['graph_dark_theme'] else 'white'
    rootgraph.attr(fontcolor=font_edge_color)

    # This can be used to visually 'inline' all subworkflows (but NOT the CWL).
    # rootgraph.attr(style='invis')
    # Note that since invisible objects still affect the graphviz layout (by design),
    # this can be used to control the layout of the individual nodes, even if
    # you don't necessarily want subworkflows.

    # rootgraph.attr(rankdir='LR') # When --graph_inline_depth 1, this usually looks better.
    with rootgraph.subgraph(name=f'cluster_{yaml_path}') as subgraph_gv:
        # get the label (if any) from the workflow
        # The root's own `wic: graphviz:` label, read from the document that
        # is compiled.
        root = bundle.parsed.document
        drawn = dict(root.sidecar.entries).get('graphviz') if root and root.sidecar else None
        label = drawn.get('label', yaml_path) if isinstance(drawn, dict) else yaml_path
        subgraph_gv.attr(label=label)
        subgraph_gv.attr(color='lightblue')  # color of cluster subgraph outline
        subgraph_nx = nx.DiGraph()
        graphdata = GraphData(yaml_path)
        subgraph = GraphReps(subgraph_gv, subgraph_nx, graphdata)

        try:
            result = compiler.compile_source(
                bundle, compiler_options, graph_settings,
                relative_run_path=True, testing=False, graph_target=subgraph)
            analyses = realtime.compile_analyses(result.realtime, yml_paths, tools_cwl,
                                                 compiler_options, graph_settings)
        except SophiosError:
            # The library reports; only this adapter is allowed to exit. The
            # banner has to stay: this arm intercepts failures that used to
            # reach the handler below, and a message naming neither the
            # workflow nor the file is a worse error than the one it replaced.
            # `main()` prints the diagnostics, in the form asked for. No
            # traceback file, though: a reported failure is not a crash, and
            # error_<stem>.txt exists to hide stack traces users cannot act on.
            print('Failed to compile', yaml_path, file=sys.stderr)
            raise
        except Exception as e:
            # Certain constraints are conditionally dependent on values and are
            # not easily encoded in the schema, so catch them here.
            # Moreover, although we check for the existence of input files in
            # stage_input_files, we cannot encode file existence in json schema
            # to check the python_script script: tag before compile time.
            print('Failed to compile', yaml_path, file=sys.stderr)
            print(f'See error_{yaml_stem}.txt for detailed technical information.', file=sys.stderr)
            # Do not display a nasty stack trace to the user; hide it in a file.
            with open(f'error_{yaml_stem}.txt', mode='w', encoding='utf-8') as f:
                # https://mypy.readthedocs.io/en/stable/common_issues.html#python-version-and-system-platform-checks
                traceback.print_exception(type(e), value=e, tb=None, file=f)
            sys.exit(1)
        # The resolved language version is reported on every compile, not
        # only on failure — nobody should have to guess which language their
        # file was read as.
        print('Sophios lang_version:', result.lang_version)
    return rootgraph, result, analyses


#: Flags that rewrite the CWL Sophios compiled. A plain CWL workflow is not
#: compiled, so there is nothing for them to rewrite, and asking is an error.
_REWRITING_FLAGS = ('--cwl_inline_runtag', '--cwl_inline_subworkflows', '--partial_failure_enable',
                    '--docker_remove_entrypoints')


def _entries(node: yaml.Node | None) -> dict[str, yaml.Node]:
    """A YAML mapping node's values by their scalar keys; empty for any other node."""
    if not isinstance(node, yaml.MappingNode):
        return {}
    return {key.value: value for key, value in node.value if isinstance(key, yaml.ScalarNode)}


def _says(node: yaml.Node | None, *values: str) -> bool:
    """Whether `node` is a scalar spelled as one of `values`."""
    return isinstance(node, yaml.ScalarNode) and node.value in values


def _tags(root: yaml.Node) -> Iterator[str]:
    """The tag of every node under `root`, each node once (an alias shares its anchor's node)."""
    seen: set[int] = set()
    stack = [root]
    while stack:
        node = stack.pop()
        if id(node) in seen:
            continue
        seen.add(id(node))
        yield node.tag
        if isinstance(node, yaml.MappingNode):
            stack.extend(child for pair in node.value for child in pair)
        elif isinstance(node, yaml.SequenceNode):
            stack.extend(node.value)


def _is_plain_cwl_workflow(path: Path) -> bool:
    """Whether `path` is a CWL workflow with no Sophios syntax in it.

    Its top level says `cwlVersion`, and either `class: Workflow` or a packed
    `$graph` whose `main` process is a Workflow; no node carries a `!` tag
    (`!ii`, `!&`, `!*`, `!cwl`) and there is no top-level `wic:`. The text is
    composed, not loaded, so a Sophios tag is seen rather than failing the read.
    A file that cannot be read or composed is not plain CWL: the compiler
    reports it as it always has.
    """
    try:
        root = yaml.compose(path.read_text(encoding='utf-8'), Loader=yaml.SafeLoader)
    except (OSError, UnicodeDecodeError, yaml.YAMLError):
        return False
    top = _entries(root)
    if 'cwlVersion' not in top or 'wic' in top:
        return False
    graph = top.get('$graph')
    packed = isinstance(graph, yaml.SequenceNode) and any(
        _says(_entries(entry).get('id'), 'main', '#main') and _says(_entries(entry).get('class'), 'Workflow')
        for entry in graph.value)
    if not (_says(top.get('class'), 'Workflow') or packed):
        return False
    return not any(tag.startswith('!') for tag in _tags(root))


def _draw(rootgraph: graphviz.Digraph | None, cwl_path: str, yaml_stem: str) -> None:
    """`--graphviz`: Sophios's drawing of the graph it compiled, if it compiled one, and cwltool's of `cwl_path`."""
    if not shutil.which('dot'):
        print("Warning: Cannot generate graphviz diagrams because the `dot` executable was not found.")
        print("(This may happen if you installed the graphviz python package")
        print("but not the graphviz system package.)")
        return
    if rootgraph is not None:
        # Not rootgraph.render(): it saves the png beside the original yaml_path.
        rootgraph.save(f'autogenerated/{yaml_stem}.wic.gv')
        cmdline = f'cat autogenerated/{yaml_stem}.wic.gv | dot -Tpng > autogenerated/{yaml_stem}.wic.gv.png'
        sub.run(cmdline, shell=True, capture_output=False, check=False)

    # For comparison, the built-in cwltool graphiz support generates a visual abomination:
    cmdline = f'cwltool_filterlog --print-dot {cwl_path} | dot -Tsvg > autogenerated/{yaml_stem}.svg'
    sub.run(cmdline, shell=True, capture_output=True, check=False)


def _run(args: argparse.Namespace, unknown_args: list[str], workflow_name: str,
         output_directories: dict[str, str] | None = None,
         documents: tuple[str, ...] | None = None,
         realtime_plans: tuple[realtime.Plan, ...] = ()) -> None:
    """Run the workflow, or write run.sh for it, with `autogenerated/` as the base path, and its real-time analyses.

    Exits with the runner's exit code when it is not 0, and with 130 on Ctrl-C.
    """
    run_args_dict = {}
    run_args_dict['container_engine'] = args.container_engine
    run_args_dict['cwl_runner'] = args.cwl_runner
    run_args_dict['copy_output_files'] = 'yes' if args.copy_output_files else 'no'
    run_args_dict['cachedir'] = args.cachedir
    run_args_dict['outdir'] = args.outdir
    run_args_dict['generate_run_script'] = 'yes' if args.generate_run_script else 'no'
    run_args_dict['quiet'] = 'yes' if args.quiet else 'no'
    try:
        retval = run_local.run_local(run_args_dict, False,
                                     workflow_name=workflow_name, passthrough_args=unknown_args,
                                     basepath='autogenerated', output_directories=output_directories,
                                     documents=documents, realtime_plans=realtime_plans)
    except KeyboardInterrupt:
        # 130 is the shell's exit code for SIGINT.
        sys.exit(130)
    if retval != 0:
        sys.exit(retval)


def _pass_through(args: argparse.Namespace, unknown_args: list[str]) -> None:
    """Use a plain CWL workflow as it is: the `--yaml` file is the artifact.

    Nothing is parsed, compiled, copied or written. The runner is given the
    file, and `--inputs_file` as its job when there is one, both as they are,
    so each resolves its relative paths against its own directory. Without
    `--inputs_file` the runner gets no job file and the workflow's defaults apply.
    """
    rewriting = [flag for flag in _REWRITING_FLAGS if getattr(args, flag[2:])]
    if rewriting:
        cli.parser.error(f'{rewriting[0]} rewrites the CWL Sophios compiles; with --allow_raw_cwl, '
                         f'{args.yaml} is a CWL workflow and is used as it is')
    workflow = Path(args.yaml).absolute()
    job = (str(Path(args.inputs_file).absolute()),) if args.inputs_file else ()
    if args.graphviz:
        Path('autogenerated').mkdir(parents=True, exist_ok=True)
        _draw(None, str(workflow), workflow.stem)
    if args.run_local or args.generate_run_script:
        pc.verify_container_engine_config(args.container_engine, args.ignore_docker_install,
                                          ignore_container_processes=args.ignore_docker_processes)
        pc.cwl_docker_extract(args.container_engine, args.pull_dir, workflow)
        Path('autogenerated').mkdir(parents=True, exist_ok=True)
        _run(args, unknown_args, workflow.stem, documents=(str(workflow), *job))
    elif args.generate_cwl_workflow:
        print(f'{args.yaml} is a CWL workflow; with --allow_raw_cwl it is used as it is, and nothing is written')
    else:
        print('Please specify either --generate_cwl_workflow (compile) or --run_local (run)')
        sys.exit(1)


def _report(diagnostics: Iterable[Diagnostic], form: str) -> None:
    """Print diagnostics on stderr, as text or as one JSON object per line."""
    for diagnostic in diagnostics:
        print(json.dumps(diagnostic.to_json()) if form == 'json' else diagnostic, file=sys.stderr)


def main() -> None:
    """CLI entry point: run, and convert a reported failure to its diagnostics and exit code 1."""
    args, unknown_args = cli.parser.parse_known_args()
    try:
        _main(args, unknown_args)
    except SophiosError as e:
        _report(e.diagnostics, args.diagnostics)
        sys.exit(1)


def _main(args: argparse.Namespace, unknown_args: list[str]) -> None:
    """See docs/userguide.md"""
    if unknown_args and args.passthrough_flags != 'yes':
        cli.parser.error(f'unrecognized arguments: {" ".join(unknown_args)}. '
                         'Flags for the CWL runner need --passthrough_flags yes')
    if unknown_args and not (args.run_local or args.generate_run_script):
        cli.parser.error(f'{" ".join(unknown_args)} would go to the CWL runner, which this command does not run. '
                         'Add --run_local or --generate_run_script, or remove them')
    plugins.logging_filters()

    # `--yaml` is required unless one of the generate modes was asked for.
    # Checked here rather than by argparse: the requirement is conditional on
    # another flag, which argparse cannot express without reading `sys.argv`
    # at import time — see the note in cli.py.
    if not args.yaml and not (args.generate_config or args.generate_schemas or args.explain):
        cli.parser.error('the following arguments are required: --yaml')
    if args.ignore_validation_errors:
        print('Warning: --ignore_validation_errors is deprecated and does nothing; '
              'nothing validates a file against a schema any more.', file=sys.stderr)

    if args.explain:
        explanation = args.explain.explanation
        print(f'{args.explain} ({explanation.kind}): {explanation.meaning}')
        print(f'Fix: {explanation.fix}')
        sys.exit(0)

    if args.generate_config:
        default_config_file = io.default_config_file(Path(args.homedir))
        if default_config_file.exists():
            print(f'Config already exists. To overwrite delete {default_config_file.parent} directory. Exiting')
        else:
            io.generate_config(Path(args.homedir))
            print('Finished generating config. Exiting.')
        sys.exit(0)
    if args.generate_schemas:
        _write_schema(SCHEMA_PATH)
        print('Finished generating schemas. Exiting.')
        sys.exit(0)
    if not Path(args.yaml).is_file():
        cli.parser.error(f'no workflow file at {args.yaml}')
    if args.inputs_file and not Path(args.inputs_file).is_file():
        cli.parser.error(f'no inputs file at {args.inputs_file}')
    if args.allow_raw_cwl and _is_plain_cwl_workflow(Path(args.yaml)):
        _pass_through(args, unknown_args)
        return
    global_config: Json = io.get_config(args.config_file, Path(args.homedir))

    tools_cwl = plugins.get_tools_cwl(global_config, args.validate_plugins, args.quiet)
    # pass around config object instead of reading from the disk!
    yml_paths = plugins.get_yml_paths(global_config)

    yaml_path, yaml_stem, bundle = _load_source_bundle(args, yml_paths, tools_cwl)

    # The one conversion from parsed arguments to settings, at the boundary.
    # Everything below this line takes values; no Namespace goes further.
    compiler_options, graph_settings = cli.get_dicts_for_compilation(args)
    compiler_options['inference_rules'] = global_config.get('inference_rules', {})
    compiler_options['renaming_conventions'] = global_config.get('renaming_conventions', [])
    rootgraph, compilation, analyses = _compile_loaded_document(
        yaml_path, yaml_stem, bundle, yml_paths, tools_cwl,
        compiler_options, graph_settings)
    _report(compilation.diagnostics, args.diagnostics)
    root_dir = Path(args.yaml).parent.absolute()
    artifact = compilation.artifact

    artifact = plugins.cwl_prepend_dockerFile_include_path_artifact(artifact)
    analyses = tuple(replace(analysis, artifact=plugins.cwl_prepend_dockerFile_include_path_artifact(analysis.artifact))
                     for analysis in analyses)

    if args.partial_failure_enable:
        artifact = plugins.cwl_update_outputs_optional_artifact(
            artifact, args.partial_failure_success_codes_range,
            args.partial_failure_success_codes)

    artifact = pc.apply_inline_options(artifact, subworkflows=args.cwl_inline_subworkflows,
                                       runtag=args.cwl_inline_runtag)

    if args.graphviz:
        _draw(rootgraph, f'autogenerated/{yaml_stem}.cwl', yaml_stem)

    if args.run_local or args.generate_run_script:
        # verify container_engine install and config
        pc.verify_container_engine_config(args.container_engine, args.ignore_docker_install,
                                          ignore_container_processes=args.ignore_docker_processes)
        # Only now we need to write the final cwl for docker-extract
        # and then for actually running using a cwl_runner
        basepath = 'autogenerated'
        io.write_artifacts_to_disk(artifact, Path(basepath), True, args.inputs_file)
        plans = realtime.write(analyses, Path(basepath), artifact.name, root_dir)
        # extract the container images, the real-time analyses' too: they run with --disable-pull
        for document in (Path(basepath) / f'{yaml_stem}.cwl', *realtime.documents(analyses, Path(basepath))):
            pc.cwl_docker_extract(args.container_engine, args.pull_dir, document)
        if args.docker_remove_entrypoints:
            artifact = pc.remove_artifact_entrypoints(args.container_engine, artifact)
            plans = realtime.write(realtime.without_entrypoints(analyses), Path(basepath), artifact.name, root_dir)
        # stage input files for run
        pc.stage_input_files(artifact.job_inputs, root_dir, basepath)
        # No need to re-write to disk as nothing of the cwl or yaml_inputs has changed!
        _run(args, unknown_args, artifact.name, run_local.output_directories(compilation.graph),
             realtime_plans=plans)

    elif args.generate_cwl_workflow:
        io.write_artifacts_to_disk(artifact, Path('autogenerated/'), True, args.inputs_file)
        realtime.write(analyses, Path('autogenerated'), artifact.name, root_dir)
    else:
        print('Please specify either --generate_cwl_workflow (compile) or --run_local (run)')
        sys.exit(1)


if __name__ == '__main__':
    main()
