import json
from pathlib import Path
import subprocess as sub
import time

import yaml


REPO_ROOT = Path(__file__).resolve().parents[1]
AUTOGENERATED = REPO_ROOT / "autogenerated"
WORKFLOW = REPO_ROOT / "examples" / "scattering_scaling.wic"
CWL_WORKFLOW = AUTOGENERATED / "scattering_scaling.cwl"
INPUTS_YML = AUTOGENERATED / "scattering_scaling_inputs.yml"
SCATTER_SIZES = (100, 200, 300, 400, 500)
MAX_QUADRATIC_COEFFICIENT = 0.001


def _run_command(cmd: list[str]) -> str:
    proc = sub.run(
        cmd,
        cwd=REPO_ROOT,
        stdout=sub.PIPE,
        stderr=sub.STDOUT,
        text=True,
        check=False,
    )
    assert proc.returncode == 0, proc.stdout
    return proc.stdout


def _quadratic_coefficient(samples: dict[int, float]) -> float:
    """Return the x^2 coefficient from a least-squares quadratic timing fit."""
    rows = [[float(size * size), float(size), 1.0] for size in samples]
    values = list(samples.values())
    normal_matrix = [
        [sum(row[i] * row[j] for row in rows) for j in range(3)]
        for i in range(3)
    ]
    normal_vector = [sum(row[i] * value for row, value in zip(rows, values)) for i in range(3)]
    augmented = [
        [*matrix_row, vector_value]
        for matrix_row, vector_value in zip(normal_matrix, normal_vector)
    ]

    for pivot in range(3):
        pivot_row = max(range(pivot, 3), key=lambda row: abs(augmented[row][pivot]))
        assert abs(augmented[pivot_row][pivot]) > 1e-12
        augmented[pivot], augmented[pivot_row] = augmented[pivot_row], augmented[pivot]

        pivot_value = augmented[pivot][pivot]
        augmented[pivot] = [value / pivot_value for value in augmented[pivot]]
        for row_index in range(3):
            if row_index == pivot:
                continue
            factor = augmented[row_index][pivot]
            augmented[row_index] = [
                current - factor * pivot_value
                for current, pivot_value in zip(augmented[row_index], augmented[pivot])
            ]

    return augmented[0][3]


def test_scattering_scaling(tmp_path: Path) -> None:
    """Run the scattering workflow at increasing sizes and guard scaling behavior.

    This is intentionally a benchmark-style CI guard, not just a functionality
    unit test. The 100..500 sweep exists to catch accidental superlinear behavior
    in scatter compilation, scheduling, or output collection. We still validate
    output cardinality and values so a fast broken run cannot pass, but the main
    regression signal is the quadratic coefficient of the timing curve. CI timing
    is noisy, so this fails only on a large positive quadratic term; negative
    curvature is usually fixed process startup overhead or filesystem cache noise.
    """
    _run_command(["sophios", "--yaml", str(WORKFLOW), "--generate_run_script", "--quiet"])

    times: dict[int, float] = {}
    for maxval in SCATTER_SIZES:
        inputs = yaml.safe_load(INPUTS_YML.read_text(encoding="utf-8"))
        inputs["scattering_scaling__step__1__array_int___maxval"] = maxval
        INPUTS_YML.write_text(yaml.safe_dump(inputs, sort_keys=False), encoding="utf-8")

        summary_path = tmp_path / f"summary_{maxval}.json"
        outdir = tmp_path / f"out_{maxval}"
        start = time.perf_counter()
        _run_command([
            "cwltool",
            "--quiet",
            "--parallel",
            "--outdir",
            str(outdir),
            "--write-summary",
            str(summary_path),
            str(CWL_WORKFLOW),
            str(INPUTS_YML),
        ])
        times[maxval] = time.perf_counter() - start

        summary = json.loads(summary_path.read_text(encoding="utf-8"))
        expected_ints = list(range(1, maxval + 1))
        expected_strings = [str(value) for value in expected_ints]

        assert summary["scattering_scaling__step__1__array_int___array"] == expected_ints
        assert summary["scattering_scaling__step__2__toString___output"] == expected_strings

        stdout_files = summary["scattering_scaling__step__3__echo___stdout"]
        assert len(stdout_files) == maxval
        assert [
            Path(stdout_file["path"]).read_text(encoding="utf-8").strip()
            for stdout_file in stdout_files
        ] == expected_strings

    quadratic_coefficient = _quadratic_coefficient(times)
    timing_report = ", ".join(f"{size}: {elapsed:.3f}s" for size, elapsed in times.items())
    assert quadratic_coefficient < MAX_QUADRATIC_COEFFICIENT, (
        "Scattering timing has an unexpectedly large positive quadratic term: "
        f"{quadratic_coefficient:.6f}. Timings: {timing_report}"
    )
