from contextlib import contextmanager
import json
import os
from pathlib import Path
import traceback
from types import SimpleNamespace
from typing import Any, Iterator
from unittest.mock import patch

import pytest
import yaml

import sophios
import sophios.apis.python as python_api_package
import sophios.apis.python._workflow_runtime as python_runtime
import sophios.plugins
import sophios.run_local as run_local
from sophios import input_output as io
from sophios import utils, utils_cwl
from sophios.apis.python.cwl_builder import CommandLineTool, Input, Inputs, Output, Outputs, cwl
from sophios.apis.python.api import InvalidLinkError, Step, Workflow
from sophios.python_cwl_adapter import import_python_file
from sophios.schemas import wic_schema
from sophios.utils_yaml import wic_loader
from sophios.wic_types import Json, Tools


REPO_ROOT = Path(__file__).resolve().parent.parent
ADAPTERS = REPO_ROOT / "cwl_adapters"
AUTOGENERATED_DIR = REPO_ROOT / "autogenerated"
PYTHON_WORKFLOW_MANIFEST = AUTOGENERATED_DIR / "python_workflow_manifest.json"


def _adapter(name: str) -> Path:
    return ADAPTERS / f"{name}.cwl"


def _load_global_config() -> Json:
    config_file = Path().home() / "wic" / "global_config.json"
    return io.read_config_from_disk(config_file)


def _iter_python_workflow_paths(global_config: Json) -> list[tuple[str, Path]]:
    paths = sophios.plugins.get_py_paths(global_config)
    return [
        (path_str, path)
        for _, paths_dict in paths.items()
        for path_str, path in paths_dict.items()
        if "mm-workflows" not in str(path) and "docs/tutorials/" not in str(path)
    ]


@contextmanager
def _step_registry_injected(tool_registry: Tools) -> Iterator[None]:
    """Inject a default tool registry into imported Python workflow scripts.

    Args:
        tool_registry (Tools): Registry of known CWL tools used for path fallback.

    Yields:
        Iterator[None]: Context where imported scripts see the patched ``Step``.
    """
    from sophios.apis.python import api  # pylint: disable=C0415:import-outside-toplevel

    step_class = api.Step

    def step_factory(*args: Any, **kwargs: Any) -> Any:
        kwargs.setdefault("tool_registry", tool_registry)
        return step_class(*args, **kwargs)

    with patch.object(api, "Step", step_factory):
        yield


def _write_manifest(workflow_paths: list[Path]) -> None:
    AUTOGENERATED_DIR.mkdir(parents=True, exist_ok=True)
    manifest = sorted({str(path) for path in workflow_paths})
    PYTHON_WORKFLOW_MANIFEST.write_text(json.dumps(manifest, indent=2), encoding="utf-8")


@pytest.mark.fast
def test_explicit_step_ports_match_legacy_yaml() -> None:
    touch_legacy = Step(_adapter("touch"))
    touch_legacy.filename = "empty.txt"
    append_legacy = Step(_adapter("append"))
    append_legacy.file = touch_legacy.file
    append_legacy.str = "Hello"

    touch_explicit = Step(_adapter("touch"))
    touch_explicit.inputs.filename = "empty.txt"
    append_explicit = Step(_adapter("append"))
    append_explicit.inputs.file = touch_explicit.outputs.file
    append_explicit.inputs.str = "Hello"

    legacy_yaml = Workflow([touch_legacy, append_legacy], "wf").yaml
    explicit_yaml = Workflow([touch_explicit, append_explicit], "wf").yaml

    assert legacy_yaml == explicit_yaml


@pytest.mark.fast
def test_in_memory_cwl_step_compiles_through_workflow_api() -> None:
    tool = (
        CommandLineTool(
            "echo_tool",
            Inputs(message=Input(cwl.string, position=1)),
            Outputs(out=Output.stdout()),
        )
        .base_command("echo")
        .stdout("stdout.txt")
    )
    step = Step.from_cwl(tool.to_dict(), process_name="say_hello")
    step.inputs.message = "hello"

    compiled = Workflow([step], "wf").get_cwl_workflow()

    assert compiled["class"] == "Workflow"
    assert compiled["steps"][0]["id"].endswith("say_hello")
    assert compiled["steps"][0]["run"]["class"] == "CommandLineTool"
    assert compiled["steps"][0]["run"]["baseCommand"] == "echo"


@pytest.mark.fast
def test_cwl_builder_workflow_example_compiles() -> None:
    example_path = REPO_ROOT / "examples" / "scripts" / "cwl_builder_workflow.py"
    module = import_python_file(example_path.stem, example_path.resolve())

    workflow = module.build_workflow("hello from test")
    compiled = workflow.get_cwl_workflow()

    assert compiled["class"] == "Workflow"
    step_ids = [step["id"] for step in compiled["steps"]]
    assert step_ids[0].endswith("emit_text")
    assert step_ids[1].endswith("read_text")
    assert compiled["outputs"]["result"]["outputSource"] == f"{step_ids[1]}/result"


@pytest.mark.fast
def test_falsey_inline_values_are_preserved() -> None:
    echo = Step(_adapter("echo"))
    echo.inputs.message = ""

    workflow_yaml = Workflow([echo], "wf").yaml
    assert workflow_yaml["steps"][0]["in"]["message"] == {"wic_inline_input": ""}


@pytest.mark.fast
def test_subworkflow_inputs_use_child_workflow_name_and_formal_parameters() -> None:
    touch = Step(_adapter("touch"))
    touch.inputs.filename = "empty.txt"

    sub_step = Step(_adapter("append"))
    subworkflow = Workflow([sub_step], "child")
    sub_step.inputs.file = subworkflow.inputs.file
    sub_step.inputs.str = subworkflow.inputs.str

    subworkflow.inputs.file = touch.outputs.file
    subworkflow.inputs.str = "Hello"

    root_yaml = Workflow([touch, subworkflow], "root").yaml
    subworkflow_step = root_yaml["steps"][1]

    assert subworkflow_step["id"] == "child.wic"
    assert subworkflow_step["parentargs"] == {
        "in": {
            "file": {"wic_alias": "filechild"},
            "str": {"wic_inline_input": "Hello"},
        }
    }
    assert subworkflow_step["subtree"]["inputs"] == {
        "file": {"type": "File"},
        "str": {"type": "string"},
    }
    assert subworkflow_step["subtree"]["steps"][0]["in"]["file"] == "file"
    assert subworkflow_step["subtree"]["steps"][0]["in"]["str"] == "str"


@pytest.mark.fast
def test_inline_subworkflow_always_emits_parentargs_key() -> None:
    sub_step = Step(_adapter("append"))
    subworkflow = Workflow([sub_step], "child")

    root_yaml = Workflow([subworkflow], "root").yaml
    subworkflow_step = root_yaml["steps"][0]

    assert subworkflow_step["id"] == "child.wic"
    assert subworkflow_step["parentargs"] == {}


@pytest.mark.fast
def test_step_unknown_attribute_raises_immediately() -> None:
    append = Step(_adapter("append"))

    with pytest.raises(AttributeError, match="has no input named"):
        append.misspelled = "Hello"


@pytest.mark.fast
def test_incompatible_step_link_raises_invalid_link_error() -> None:
    touch = Step(_adapter("touch"))
    touch.inputs.filename = "empty.txt"
    append = Step(_adapter("append"))

    with pytest.raises(InvalidLinkError, match="incompatible types"):
        append.inputs.str = touch.outputs.file


@pytest.mark.fast
def test_workflow_outputs_are_serialized_with_type_and_source() -> None:
    touch = Step(_adapter("touch"))
    touch.inputs.filename = "empty.txt"

    append = Step(_adapter("append"))
    append.inputs.file = touch.outputs.file
    append.inputs.str = "Hello"

    workflow = Workflow([touch, append], "wf")
    workflow.outputs.file = append.outputs.file

    workflow_yaml = workflow.yaml

    assert workflow_yaml["outputs"] == {
        "file": {"type": "File", "outputSource": "append/file"},
    }


@pytest.mark.fast
def test_config_yaml_normalizes_cwl_file_and_directory_objects(tmp_path: Path) -> None:
    input_dir = tmp_path / "input-dir"
    input_dir.mkdir()
    input_file = tmp_path / "input.txt"
    input_file.write_text("hello", encoding="utf-8")

    subdirectory_cfg = tmp_path / "subdirectory.yml"
    subdirectory_cfg.write_text(
        yaml.safe_dump(
            {
                "directory": {"class": "Directory", "location": str(input_dir)},
                "glob_pattern": ".",
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )
    subdirectory = Step(_adapter("subdirectory"), config_path=subdirectory_cfg)
    assert subdirectory._yml["in"]["directory"] == {"wic_inline_input": str(input_dir)}

    append_cfg = tmp_path / "append.yml"
    append_cfg.write_text(
        yaml.safe_dump(
            {
                "file": {"class": "File", "location": str(input_file)},
                "str": "Hello",
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )
    append = Step(_adapter("append"), config_path=append_cfg)
    assert append._yml["in"]["file"] == {"wic_inline_input": str(input_file)}


@pytest.mark.fast
def test_scatter_rejects_unbound_foreign_or_scalar_inputs() -> None:
    echo = Step(_adapter("echo"))
    other_echo = Step(_adapter("echo"))

    with pytest.raises(ValueError, match="bound before scattering"):
        echo.scatter = [echo.inputs.message]

    echo.inputs.message = "hello"
    with pytest.raises(ValueError, match="array-valued data"):
        echo.scatter = [echo.inputs.message]

    other_echo.inputs.message = ["a", "b"]
    with pytest.raises(ValueError, match="belong to the same step"):
        echo.scatter = [other_echo.inputs.message]


@pytest.mark.fast
def test_top_level_python_api_exports_only_user_facing_names() -> None:
    assert not hasattr(python_api_package, "WorkflowInputReference")
    assert not hasattr(python_api_package, "set_input_Step_Workflow")
    assert not hasattr(python_api_package, "extract_tools_paths_NONPORTABLE")


@pytest.mark.fast
def test_run_local_subprocess_uses_explicit_env_without_global_mutation(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    run_args = {
        "container_engine": "docker",
        "cwl_runner": "cwltool",
    }
    seen_env: dict[str, str] = {}
    sentinel_key = "SOPHIOS_TEST_SUBPROCESS_ENV"
    os.environ.pop(sentinel_key, None)

    def fake_run(cmd: list[str], check: bool, env: dict[str, str]) -> SimpleNamespace:
        del cmd, check
        seen_env.update(env)
        return SimpleNamespace(returncode=0)

    monkeypatch.setattr(run_local.sub, "run", fake_run)

    retval = run_local.run_local(
        run_args,
        True,
        passthrough_args=[],
        workflow_name="wf",
        basepath="autogenerated",
        user_env_vars={sentinel_key: "hello"},
    )

    assert retval == 0
    assert seen_env[sentinel_key] == "hello"
    assert sentinel_key not in os.environ


@pytest.mark.fast
def test_run_local_python_api_restores_environment_after_run(monkeypatch: pytest.MonkeyPatch) -> None:
    run_args = {
        "container_engine": "docker",
        "cwl_runner": "cwltool",
    }
    sentinel_key = "SOPHIOS_TEST_PYAPI_ENV"
    os.environ.pop(sentinel_key, None)
    seen_inside: dict[str, str | None] = {"value": None}

    def fake_main(args: list[str]) -> int:
        del args
        seen_inside["value"] = os.environ.get(sentinel_key)
        return 0

    monkeypatch.setattr(run_local.cwltool.main, "main", fake_main)

    retval = run_local.run_local(
        run_args,
        False,
        passthrough_args=[],
        workflow_name="wf",
        basepath="autogenerated",
        user_env_vars={sentinel_key: "inside"},
    )

    assert retval == 0
    assert seen_inside["value"] == "inside"
    assert sentinel_key not in os.environ


@pytest.mark.fast
def test_workflow_run_uses_basepath_for_docker_extract(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    example_path = REPO_ROOT / "examples" / "scripts" / "cwl_builder_workflow.py"
    module = import_python_file(example_path.stem, example_path.resolve())
    workflow = module.build_workflow("hello from test")
    calls: dict[str, list[tuple[Any, ...]]] = {"verify": [], "extract": []}

    def fake_verify(container_engine: str, ignore_install: bool) -> None:
        calls["verify"].append((container_engine, ignore_install))

    def fake_extract(container_engine: str, pull_dir: str, cwl_path: Path) -> None:
        calls["extract"].append((container_engine, pull_dir, cwl_path))

    def fake_run_local(
        run_args_dict: dict[str, str],
        use_subprocess: bool,
        passthrough_args: list[str],
        workflow_name: str,
        basepath: str,
        user_env_vars: dict[str, str] | None = None,
    ) -> int:
        del run_args_dict, use_subprocess, passthrough_args, workflow_name, basepath, user_env_vars
        return 0

    monkeypatch.setattr(python_runtime.pc, "verify_container_engine_config", fake_verify)
    monkeypatch.setattr(python_runtime.pc, "cwl_docker_extract", fake_extract)
    monkeypatch.setattr(python_runtime.rl, "run_local", fake_run_local)

    workflow.run(basepath=str(tmp_path))

    assert calls["verify"] == [("docker", False)]
    assert calls["extract"] == [("docker", str(Path.cwd()), tmp_path / "cwl_builder_workflow_demo.cwl")]


@pytest.mark.fast
def test_compile_python_workflows() -> None:
    """Import and compile all auto-discovered Python workflow scripts."""
    from sophios.apis.python import api  # pylint: disable=C0415:import-outside-toplevel

    global_config = _load_global_config()
    tools_cwl = sophios.plugins.get_tools_cwl(global_config)
    paths_tuples = _iter_python_workflow_paths(global_config)
    import_errors: list[str] = []
    generated_workflows: list[Path] = []
    for path_stem, path in paths_tuples:
        try:
            with _step_registry_injected(tools_cwl):
                module = import_python_file(path_stem, path)
                retval: api.Workflow = module.workflow()

            retval.compile()
            retval.write_ast_to_disk(path.parent)
            generated_workflows.extend(path.parent / f"{wf.process_name}.wic" for wf in retval.flatten_subworkflows())

            config_ci = path.parent / "config_ci.json"
            json_contents = {}
            if config_ci.exists():
                with open(config_ci, mode="r", encoding="utf-8") as r:
                    json_contents = json.load(r)
            run_blacklist: list[str] = json_contents.get("run_blacklist", [])
            subworkflows: list[api.Workflow] = retval.flatten_subworkflows()[1:]
            run_blacklist += [wf.process_name for wf in subworkflows]
            json_contents["run_blacklist"] = run_blacklist
            with open(config_ci, mode="w", encoding="utf-8") as f:
                json.dump(json_contents, f)

        except Exception as exc:  # pylint: disable=W0718:broad-exception-caught
            import_errors.append(f"{path_stem}: {type(exc).__name__}: {exc}")
            traceback.print_exception(type(exc), value=exc, tb=None)
    if import_errors:
        pytest.fail("Python workflow imports failed:\n" + "\n".join(import_errors))
    _write_manifest(generated_workflows)


@pytest.mark.fast
def test_validate_generated_python_workflows() -> None:
    if not PYTHON_WORKFLOW_MANIFEST.exists():
        pytest.fail(f"Missing generated workflow manifest: {PYTHON_WORKFLOW_MANIFEST}")

    global_config = _load_global_config()
    tools_cwl = sophios.plugins.get_tools_cwl(global_config)
    yml_paths = sophios.plugins.get_yml_paths(global_config)
    yaml_stems = utils.flatten([list(paths) for paths in yml_paths.values()])
    validator = wic_schema.get_validator(tools_cwl, yaml_stems, {}, write_to_disk=False)

    workflow_paths = json.loads(PYTHON_WORKFLOW_MANIFEST.read_text(encoding="utf-8"))
    validation_errors: list[str] = []
    for workflow_path_str in workflow_paths:
        workflow_path = Path(workflow_path_str)
        try:
            with workflow_path.open("r", encoding="utf-8") as handle:
                yaml_tree = yaml.load(handle.read(), Loader=wic_loader())
            validator.validate(utils_cwl.desugar_into_canonical_normal_form(yaml_tree))
        except Exception as exc:  # pylint: disable=W0718:broad-exception-caught
            validation_errors.append(f"{workflow_path}: {type(exc).__name__}: {exc}")

    if validation_errors:
        pytest.fail("Generated workflow validation failed:\n" + "\n".join(validation_errors))
