import asyncio
import copy
import json
from pathlib import Path
import subprocess as sub
import traceback

from fastapi import Request
import pytest
import yaml

import sophios.post_compile as pc
from sophios.apis.rest import api
from sophios.wic_types import Json, List

try:
    import cwltool.main
    import toil.cwl.cwltoil  # transitively imports cwltool
except ImportError as exc:
    print("Could not import cwltool.main and/or toil.cwl.cwltoil")
    print(exc)
    if exc.msg == "No module named 'pwd'":
        print("Windows does not have a pwd module")
        print("If you want to run on windows, you need to install")
        print("Windows Subsystem for Linux")
        print("See https://pypi.org/project/cwltool/#ms-windows-users")
    else:
        raise exc


REST_OBJECTS = Path(__file__).parent / "rest_wfb_objects"


def run_cwl_local(workflow_name: str, cwl_runner: str, docker_cmd: str, use_subprocess: bool) -> int:
    """Run compiled CWL output via a supported CWL runner.

    Args:
        workflow_name (str): Stem of the generated workflow files in ``autogenerated/``.
        cwl_runner (str): CWL runner entrypoint to invoke.
        docker_cmd (str): Container engine selector passed through to the runner.
        use_subprocess (bool): Whether to invoke the runner as a subprocess.

    Returns:
        int: Exit code returned by the CWL runner.
    """
    quiet = ["--quiet"]
    skip_schemas = ["--skip-schemas"]
    provenance = ["--provenance", f"provenance/{workflow_name}"]
    docker_cmd_: List[str] = []
    if docker_cmd == "docker":
        docker_cmd_ = []
    elif docker_cmd == "singularity":
        docker_cmd_ = ["--singularity"]
    else:
        docker_cmd_ = ["--user-space-docker-cmd", docker_cmd]
    write_summary = ["--write-summary", f"output_{workflow_name}.json"]
    path_check = ["--relax-path-checks"]
    docker_pull = ["--disable-pull"]
    script = "cwltool_filterlog" if cwl_runner == "cwltool" else cwl_runner
    cmd = [script] + docker_pull + quiet + provenance + docker_cmd_ + write_summary + skip_schemas + path_check
    if cwl_runner == "cwltool":
        cmd += [
            "--leave-outputs",
            f"autogenerated/{workflow_name}.cwl",
            f"autogenerated/{workflow_name}_inputs.yml",
        ]
    elif cwl_runner == "toil-cwl-runner":
        cmd += [
            "--outdir",
            "outdir_toil",
            "--jobStore",
            f"file:./jobStore_{workflow_name}",
            "--clean",
            "always",
            f"autogenerated/{workflow_name}.cwl",
            f"autogenerated/{workflow_name}_inputs.yml",
        ]

    retval = 1
    print("Running " + " ".join(cmd))
    if use_subprocess:
        proc = sub.run(cmd, check=False)
        retval = proc.returncode
    else:
        print("via cwltool.main.main python API")
        try:
            if cwl_runner == "cwltool":
                retval = cwltool.main.main(cmd[1:])
            elif cwl_runner == "toil-cwl-runner":
                retval = toil.cwl.cwltoil.main(cmd[1:])
            else:
                raise Exception("Invalid cwl_runner!")

            print(f"Final output json metadata blob is in output_{workflow_name}.json")
        except Exception as exc:  # pylint: disable=W0718:broad-exception-caught
            print("Failed to execute", workflow_name)
            print(f"See error_{workflow_name}.txt for detailed technical information.")
            with open(f"error_{workflow_name}.txt", mode="w", encoding="utf-8") as f:
                traceback.print_exception(type(exc), value=exc, tb=None, file=f)
            print(exc)
    return retval


def write_out_to_disk(res: Json, workflow_name: str) -> None:
    """Write compiled REST output to disk before invoking a CWL runner.

    Args:
        res (Json): REST API response containing compiled CWL and input bindings.
        workflow_name (str): Stem to use for generated output files.
    """
    res_cwl = copy.deepcopy(res)
    res_cwl.pop("retval", None)
    res_cwl.pop("cwlJobInputs", None)
    res_cwl.pop("name", None)
    compiled_cwl = workflow_name + ".cwl"
    inputs_yml = workflow_name + "_inputs.yml"
    with open(Path.cwd() / "autogenerated" / compiled_cwl, "w", encoding="utf-8") as f:
        yaml.dump(res_cwl, f)
    with open(Path.cwd() / "autogenerated" / inputs_yml, "w", encoding="utf-8") as f:
        yaml.dump(res["cwlJobInputs"], f)


def prepare_call_rest_api(inp_path: Path) -> Json:
    """Load a REST payload fixture and compile it through the REST API.

    Args:
        inp_path (Path): Path to the JSON fixture to submit.

    Returns:
        Json: Response returned by ``compile_wf``.
    """
    with open(inp_path, "r", encoding="utf-8") as f:
        inp = json.load(f)
    scope = {"type": "http"}

    async def receive() -> Json:
        inp_byte = json.dumps(inp).encode("utf-8")
        return {"type": "http.request", "body": inp_byte}

    req: Request = Request(scope)
    req._receive = receive
    return asyncio.run(api.compile_wf(req))


@pytest.mark.skip_pypi_ci
@pytest.mark.parametrize(
    "inp_file",
    [
        "single_node.json",
        "single_node_bbbc_download.json",
        "bbbc_download_wfb.json",
        "multi_node.json",
        "multi_node_inline_cwl.json",
    ],
)
def test_rest_core_runs_workflow(inp_file: str) -> None:
    """Compile representative REST payloads and run the resulting workflows.

    Args:
        inp_file (str): Fixture filename under ``tests/rest_wfb_objects``.
    """
    basepath = "autogenerated"
    inp_path = REST_OBJECTS / inp_file
    workflow_name = inp_file.split(".", maxsplit=1)[0]
    res = prepare_call_rest_api(inp_path)
    output_dirs = pc.find_output_dirs(res)
    pc.create_output_dirs(output_dirs, basepath)
    write_out_to_disk(res, workflow_name)
    retval = run_cwl_local(workflow_name, "cwltool", "docker", False)
    assert retval == 0


def test_rest_wfb_compile() -> None:
    """Compile a WFB-originated payload through the REST API.

    Returns:
        None: The assertion verifies a successful compile.
    """
    inp_path = REST_OBJECTS / "multi_node_wfb.json"
    res = prepare_call_rest_api(inp_path)
    assert int(res["retval"]) == 0
