from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import pytest
import yaml

import sophios
import sophios.cli
import sophios.input_output as io
import sophios.plugins
import sophios.api
import sophios.api.python.workflow
from sophios.wic_types import Json, Tools
from sophios.utils_yaml import wic_loader


@dataclass(frozen=True, slots=True)
class CorpusRegistry:
    """The explicit environment-dependent inputs used by corpus tests."""

    tools: Tools
    workflows: dict[str, dict[str, Path]]


def _config() -> tuple[Json, bool]:
    """Read configuration without provisioning a missing user config."""
    args = sophios.cli.get_args()
    config_file = args.config_file or io.default_config_file(Path(args.homedir))
    if config_file.exists():
        return io.read_config_from_disk(config_file), args.quiet
    return io.get_basic_config(), args.quiet


@lru_cache(maxsize=1)
def workflow_paths() -> dict[str, dict[str, Path]]:
    """Discover workflow source paths without loading any process plugins."""
    config, _ = _config()
    paths: dict[str, dict[str, Path]] = sophios.plugins.get_yml_paths(config)
    return paths


def yml_path_is_workflow(yml_path: Path) -> bool:
    """Return whether a `.wic` file looks like a compilable workflow root.

    Args:
        yml_path (Path): Path to a workflow-definition file.

    Returns:
        bool: True when the file declares steps or workflow implementations.
    """
    with open(yml_path, mode='r', encoding='utf-8') as yml_file:
        yml = yaml.load(yml_file.read(), Loader=wic_loader())
    if not isinstance(yml, dict):
        return False
    wic_tag = yml.get('wic', {})
    return (
        'steps' in yml
        or 'implementations' in yml
        or (isinstance(wic_tag, dict) and 'implementations' in wic_tag)
    )


@lru_cache(maxsize=1)
def load_test_registry() -> CorpusRegistry:
    """Discover tools and workflows on first test execution, never at collection.

    Importing this module therefore cannot discover CWL plugins or write under
    ``autogenerated/``.
    """
    config, quiet = _config()
    return CorpusRegistry(sophios.plugins.get_tools_cwl(config, quiet=quiet), workflow_paths())


@pytest.fixture(scope='session')
def corpus_registry() -> CorpusRegistry:
    """Explicit registry fixture for tests that exercise the discovered corpus."""
    return load_test_registry()
