from contextlib import contextmanager
import asyncio
import copy
import dataclasses
import decimal
import importlib
import json
import os
import pickle
from pathlib import Path
import subprocess
import sys
import traceback
import warnings
from types import SimpleNamespace
from typing import Any, Callable, Iterator, cast
from unittest.mock import patch

import cwltool.utils
from jsonschema import Draft202012Validator
import pytest
import yaml

import sophios
import sophios.api.python as python_api_package
import sophios.api.python._workflow_runtime as python_runtime
import sophios.compiler
import sophios.compute_request as compute_request_module
import sophios.plugins
from sophios import input_output as io
from sophios import run_local
from sophios import run_local_async
from sophios.api.python.tool_builder import CommandLineTool, Input, Inputs, Output, Outputs, cwl
from sophios.api.python.workflow import (_python_api_types_match, ApiError, CompiledWorkflow,
                                         InvalidCLTError, InvalidInputValueError, InvalidLinkError,
                                         InvalidStepError, SophiosError, SophiosErrorCode, Step,
                                         StepInput, Workflow)
from sophios.cli import default_compilation_settings
from sophios.lang import CwlRecord, InlineLiteral, parse, to_json, wic_schema
from sophios.compute_request import ComputeExecutionConfig, ComputeOutputConfig, ComputeRequest, ComputeSubmission
from sophios.ir.frontdoor import bundle_from_disk
from sophios.post_compile import inline_artifact_runs
from sophios.python_cwl_adapter import import_python_file
from sophios.runtime_inputs import normalize_artifact_cwl
from sophios.utils_graphs import get_graph_reps
from sophios.utils_yaml import wic_loader
from sophios.wic_types import Json, Tools


REPO_ROOT = Path(__file__).resolve().parents[2]
ADAPTERS = REPO_ROOT / "cwl_adapters"
AUTOGENERATED_DIR = REPO_ROOT / "autogenerated"
PYTHON_WORKFLOW_MANIFEST = AUTOGENERATED_DIR / "python_workflow_manifest.json"


def _adapter(name: str) -> Path:
    """The path to a packaged CWL adapter, by stem."""
    return ADAPTERS / f"{name}.cwl"


def _emit_text_tool() -> CommandLineTool:
    """A minimal built tool that writes its message to a file."""
    return (
        CommandLineTool(
            "emit_text",
            Inputs(message=Input(cwl.string, position=1)),
            Outputs(file=Output(cwl.file, glob="stdout.txt")),
        )
        .base_command("echo")
        .stdout("stdout.txt")
    )


def _output_directory_tool(path: Path) -> Path:
    """A built tool whose output is a directory it names itself."""
    path.write_text(
        """class: CommandLineTool
cwlVersion: v1.2
requirements:
  InitialWorkDirRequirement:
    listing:
      - entry: $(inputs.outDir)
        writable: true
  InlineJavascriptRequirement: {}
baseCommand: [bash, -lc]
arguments:
  - valueFrom: "touch $(inputs.outDir.basename)/done.txt"
inputs:
  outDir:
    type: Directory
    inputBinding:
      prefix: --outDir
outputs:
  outDir:
    type: Directory
    outputBinding:
      glob: $(inputs.outDir.basename)
""",
        encoding="utf-8",
    )
    return path


def _load_global_config() -> Json:
    """The config CI provisions, read from the user's home."""
    config_file = Path().home() / "wic" / "global_config.json"
    return io.read_config_from_disk(config_file)


def _iter_python_workflow_paths(global_config: Json) -> list[tuple[str, Path]]:
    """Every discovered Python workflow, minus the corpora with their own lanes."""
    paths = sophios.plugins.get_workflow_paths(global_config, 'py')
    return [
        (path_str, path)
        for _, paths_dict in paths.items()
        for path_str, path in paths_dict.items()
        if "mm-workflows" not in str(path) and "docs/tutorials/" not in str(path)
    ]


@contextmanager
def _step_registry_injected(tool_registry: Tools) -> Iterator[None]:
    """Inject a default tool registry into imported Python workflow scripts,
    so they see the patched ``Step``."""
    from sophios.api.python import workflow  # pylint: disable=C0415:import-outside-toplevel

    step_class = workflow.Step

    def step_factory(*args: Any, **kwargs: Any) -> Any:
        kwargs.setdefault("tool_registry", tool_registry)
        return step_class(*args, **kwargs)

    with patch.object(workflow, "Step", step_factory):
        yield


def _write_manifest(workflow_paths: list[Path]) -> None:
    """Record the generated `.wic` paths for the validation step that follows."""
    AUTOGENERATED_DIR.mkdir(parents=True, exist_ok=True)
    manifest = sorted({str(path) for path in workflow_paths})
    PYTHON_WORKFLOW_MANIFEST.write_text(
        json.dumps(manifest, indent=2), encoding="utf-8")


@pytest.mark.fast
def test_explicit_ports_and_attribute_sugar_produce_one_document() -> None:
    """`step.inputs.x` and the bare `step.x` sugar are the same binding.

    Both spellings are the Python API's -- this compares them to each other,
    not to the YAML front end. The sugar resolves through `__getattr__`, so it
    is the spelling that can silently diverge.
    """
    touch_legacy = Step(clt_path=_adapter("touch"))
    touch_legacy.filename = "empty.txt"
    append_legacy = Step(clt_path=_adapter("append"))
    append_legacy.file = touch_legacy.file
    append_legacy.str = "Hello"

    touch_explicit = Step(clt_path=_adapter("touch"))
    touch_explicit.inputs.filename = "empty.txt"
    append_explicit = Step(clt_path=_adapter("append"))
    append_explicit.inputs.file = touch_explicit.outputs.file
    append_explicit.inputs.str = "Hello"

    legacy_yaml = Workflow([touch_legacy, append_legacy], "wf").yaml
    explicit_yaml = Workflow([touch_explicit, append_explicit], "wf").yaml

    assert legacy_yaml == explicit_yaml


@pytest.mark.fast
def test_linear_python_workflow_reuses_compiler_edge_inference() -> None:
    """An unbound input is left for inference, not guessed by the API.

    The exported document omits `file` entirely and the compiled one names the
    producing step, so inference ran rather than the API pre-resolving it."""
    touch = Step(clt_path=_adapter("touch"))
    touch.inputs.filename = "empty.txt"

    append = Step(clt_path=_adapter("append"))
    append.inputs.str = "Hello"

    cat = Step(clt_path=_adapter("cat"))

    workflow = Workflow([touch, append, cat], "wf")
    workflow_yaml = workflow.yaml
    assert "file" not in workflow_yaml["steps"][1]["in"]
    assert "file" not in workflow_yaml["steps"][2].get("in", {})

    compiled = workflow.compile()

    assert compiled.cwl_workflow["steps"][1]["in"]["file"] == "wf__step__1__touch/file"
    assert compiled.cwl_workflow["steps"][2]["in"]["file"] == "wf__step__2__append/file"
    assert compiled.cwl_job_inputs == {
        "wf__step__1__touch___filename": "empty.txt",
        "wf__step__2__append___str": "Hello",
    }


@pytest.mark.fast
def test_compiled_workflow_carries_the_inference_notes() -> None:
    """A choice between equal producers is on the compiled object, not a warning."""
    first = Step(clt_path=_adapter("touch"), step_name="first")
    first.inputs.filename = "a.txt"
    second = Step(clt_path=_adapter("touch"), step_name="second")
    second.inputs.filename = "b.txt"
    cat = Step(clt_path=_adapter("cat"))

    compiled = Workflow([first, second, cat], "wf").compile()

    (note,) = compiled.diagnostics
    assert "note [wic043]" in note
    assert "'cat'" in note and "step 1 'first' output 'file'" in note


@pytest.mark.fast
def test_in_memory_cwl_step_compiles_through_workflow_api() -> None:
    """A tool given as a document compiles without ever being written to disk."""
    tool = (
        CommandLineTool(
            "echo_tool",
            Inputs(message=Input(cwl.string, position=1)),
            Outputs(out=Output.stdout()),
        )
        .base_command("echo")
        .stdout("stdout.txt")
    )
    step = Step.from_cwl_document(tool.to_cwl_document(), process_name="say_hello")
    step.inputs.message = "hello"

    compiled = Workflow([step], "wf").compile()

    assert compiled.cwl_workflow["class"] == "Workflow"
    assert compiled.cwl_workflow["steps"][0]["id"].endswith("say_hello")
    assert compiled.cwl_workflow["steps"][0]["run"]["class"] == "CommandLineTool"
    assert compiled.cwl_workflow["steps"][0]["run"]["baseCommand"] == "echo"


@pytest.mark.fast
def test_a_numpy_float_reaches_the_job_as_a_plain_float() -> None:
    """numpy's float64 is a float, and a job file holds plain numbers."""
    numpy = pytest.importorskip("numpy")
    tool = (
        CommandLineTool(
            "scale_tool",
            Inputs(factor=Input(cwl.float, position=1)),
            Outputs(out=Output.stdout()),
        )
        .base_command("echo")
        .stdout("stdout.txt")
    )
    step = Step.from_cwl_document(tool.to_cwl_document(), process_name="scale")
    step.inputs.factor = numpy.float64(0.5)

    (value,) = Workflow([step], "wf").compile().cwl_job_inputs.values()

    assert (value, type(value)) == (0.5, float)


@pytest.mark.fast
@pytest.mark.parametrize("declared, python_type", [
    (cwl.int, "int"), (cwl.float, "float"), (cwl.boolean, "bool"), (cwl.string, "str"),
])
def test_a_value_of_another_python_type_is_wic020_naming_the_type_the_port_holds(
        declared: Any, python_type: str) -> None:
    """A numpy scalar or a Decimal is not a Python number: nothing converts it, and the message says so."""
    tool = (
        CommandLineTool(
            "scale_tool",
            Inputs(factor=Input(declared, position=1)),
            Outputs(out=Output.stdout()),
        )
        .base_command("echo")
        .stdout("stdout.txt")
    )
    step = Step.from_cwl_document(tool.to_cwl_document(), process_name="scale")
    step.inputs.factor = decimal.Decimal(3)

    with pytest.raises(SophiosError) as caught:
        Workflow([step], "wf").compile()

    diagnostic = caught.value.diagnostics[0]
    assert diagnostic.code is SophiosErrorCode.LITERAL_TYPE_MISMATCH
    assert diagnostic.message.endswith(f"is of type decimal.Decimal, not a Python {python_type}.")


@pytest.mark.fast
def test_step_constructor_accepts_tool_builder_command_line_tool() -> None:
    """A built tool becomes a step, and `step_name` renames both it and its path."""
    tool = _emit_text_tool()

    default_step = Step(tool)
    renamed_step = Step(tool, step_name="say_hello")
    renamed_step.inputs.message = "hello"

    compiled = Workflow([renamed_step], "wf").compile()

    assert default_step.process_name == "emit_text"
    assert default_step.clt_path.name == "emit_text.cwl"
    assert renamed_step.process_name == "say_hello"
    assert renamed_step.clt_path.name == "say_hello.cwl"
    assert renamed_step.yaml["class"] == "CommandLineTool"
    assert compiled.cwl_workflow["steps"][0]["id"].endswith("say_hello")
    assert compiled.cwl_workflow["steps"][0]["run"]["class"] == "CommandLineTool"
    assert compiled.cwl_workflow["steps"][0]["run"]["baseCommand"] == "echo"


@pytest.mark.fast
def test_step_constructor_rejects_config_path_for_in_memory_tool() -> None:
    """`config_path` belongs to a tool on disk; an in-memory tool has no file to configure."""
    tool = cast(Any, _emit_text_tool())
    with pytest.raises(TypeError, match="config_path is only supported"):
        Step(tool, "config.yml")


@pytest.mark.fast
def test_tool_builder_step_bridge_supports_multistep_workflow() -> None:
    """Built tools chain: two steps, ordered, with the workflow output wired through."""
    emit_step = Step(_emit_text_tool(), step_name="emit_text")
    read_step = Step(clt_path=_adapter("cat"))

    workflow = Workflow([emit_step, read_step], "builder_and_pyapi_demo")
    emit_step.inputs.message = workflow.inputs.message.as_type(cwl.string)
    read_step.inputs.file = emit_step.outputs.file
    workflow.outputs.result = read_step.outputs.output

    compiled = workflow.compile()

    assert compiled.cwl_workflow["class"] == "Workflow"
    step_ids = [step["id"] for step in compiled.cwl_workflow["steps"]]
    assert step_ids[0].endswith("emit_text")
    assert step_ids[1].endswith("cat")
    assert list(compiled.cwl_workflow["outputs"]) == ["result"]
    assert compiled.cwl_workflow["outputs"]["result"]["outputSource"] == f"{step_ids[1]}/output"


@pytest.mark.fast
def test_a_workflow_output_prints_no_authored_spelling_line(capsys: pytest.CaptureFixture[str]) -> None:
    """The Python API spells `outputSource` with generated names itself; nobody wrote that text."""
    emit_step = Step(_emit_text_tool(), step_name="emit_text")
    read_step = Step(clt_path=_adapter("cat"))
    workflow = Workflow([emit_step, read_step], "output_line_demo")
    emit_step.inputs.message = workflow.inputs.message.as_type(cwl.string)
    read_step.inputs.file = emit_step.outputs.file
    workflow.outputs.result = read_step.outputs.output

    workflow.compile()

    assert "Warning!" not in capsys.readouterr().err


@pytest.mark.fast
def test_attribute_sugar_input_warning_points_at_the_reference_and_the_typed_declaration() -> None:
    step = Step(_emit_text_tool(), step_name="emit_text")
    workflow = Workflow([step], "sugar_demo")

    with pytest.warns(UserWarning, match=r"Prefer workflow\.inputs\.message, or workflow\.inputs\.message\.as_type"):
        step.inputs.message = workflow.message


@pytest.mark.fast
def test_binding_an_input_reference_to_a_workflow_output_does_not_warn() -> None:
    workflow = Workflow([], "passthrough_demo")

    with warnings.catch_warnings():
        warnings.simplefilter("error")
        workflow.outputs.o = workflow.inputs.x


@pytest.mark.fast
def test_output_target_directories_compile_as_runner_local_inputs(tmp_path: Path) -> None:
    """A declared output directory becomes a string input the runner fills.

    Typed `string` rather than `Directory` because the directory does not exist
    until the step runs; the `glob` refers back to the input that names it."""
    step = Step(clt_path=_output_directory_tool(tmp_path / "write_dir.cwl"))
    step.inputs.outDir = Path("result.outDir")
    workflow = Workflow([step], "virtual_dir_demo")

    compiled = workflow.compile()

    assert compiled.cwl_job_inputs["virtual_dir_demo__step__1__write_dir___outDir"] == "result.outDir"
    assert compiled.cwl_workflow["inputs"]["virtual_dir_demo__step__1__write_dir___outDir"]["type"] == "string"
    assert compiled.cwl_workflow["steps"][0]["run"]["inputs"]["outDir"]["type"] == "string"
    assert compiled.cwl_workflow["steps"][0]["run"]["outputs"]["outDir"]["outputBinding"]["glob"] == "$(inputs.outDir)"


@pytest.mark.fast
def test_output_target_directories_reject_absolute_locations(tmp_path: Path) -> None:
    """An output directory is runner-local, so an absolute path is refused."""
    step = Step(clt_path=_output_directory_tool(tmp_path / "write_dir.cwl"))
    step.inputs.outDir = tmp_path / "absolute.outDir"
    workflow = Workflow([step], "absolute_dir_demo")

    with pytest.raises(ValueError, match="cannot use an absolute location"):
        workflow.compile()


@pytest.mark.fast
def test_port_namespaces_do_not_accept_string_indexing() -> None:
    """Ports are reached by attribute or by index, never by name as text.

    A string subscript would silently miss a typo; the type rejects it."""
    step = Step(_emit_text_tool())

    with pytest.raises(TypeError, match="integer indexing only"):
        step.inputs["message"]

    with pytest.raises(TypeError, match="integer indexing only"):
        step.outputs["file"]


@pytest.mark.fast
def test_compute_request_accepts_compiled_python_workflow() -> None:
    """A compiled workflow becomes a compute request whose JSON round-trips."""
    emit_step = Step(_emit_text_tool(), step_name="emit_text")
    emit_step.inputs.message = "hello from compute"

    workflow = Workflow([emit_step], "compute_request_workflow_demo")
    compiled = workflow.compile()
    request = ComputeRequest(
        compiled,
        workflow_id="compute_request_workflow_demo",
        compute_config=ComputeExecutionConfig(output=ComputeOutputConfig.workflow_declared()),
    )
    request_mapping = request.to_mapping()
    request_json = request.to_json()

    assert isinstance(request_json, str)
    assert json.loads(request_json) == request_mapping
    assert request_mapping["id"] == "compute_request_workflow_demo"
    assert request_mapping["cwlWorkflow"]["class"] == "Workflow"
    assert request_mapping["cwlWorkflow"]["steps"][0]["run"]["class"] == "CommandLineTool"
    assert request_mapping["computeConfig"]["outputConfig"]["mode"] == "workflowDeclared"
    input_key = next(iter(request_mapping["cwlJobInputs"]))
    assert input_key.endswith("emit_text___message")
    assert request_mapping["cwlJobInputs"][input_key] == "hello from compute"


@pytest.mark.fast
def test_compute_request_submit_returns_structured_submission(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    """Submission returns a typed result, not a raw response to be parsed again."""
    posted: dict[str, Any] = {}
    log_path = tmp_path / "compute.log"

    class FakeResponse:
        def __init__(self, body: Json, *, ok: bool = True, status_code: int = 200) -> None:
            self._body = body
            self.ok = ok
            self.status_code = status_code
            self.text = json.dumps(body)

        def json(self) -> Json:
            """The decoded body this stub was constructed with."""
            return self._body

    class FakeSession:
        def __enter__(self) -> "FakeSession":
            return self

        def __exit__(self, *args: object) -> None:
            return None

        def post(
            self,
            url: str,
            *,
            data: str,
            headers: dict[str, str],
            timeout: tuple[int, int],
        ) -> FakeResponse:
            """Record the submission and return the canned response."""
            posted.update(
                {
                    "url": url,
                    "data": json.loads(data),
                    "headers": headers,
                    "timeout": timeout,
                }
            )
            return FakeResponse({"ok": True})

        def get(self, url: str, *, timeout: tuple[int, int]) -> FakeResponse:
            """Return the canned response for a polled workflow."""
            del timeout
            posted.setdefault("get_urls", []).append(url)
            if url.endswith("/logs/"):
                return FakeResponse({"log": "hello"})
            return FakeResponse({"status": "RUNNING"})

    monkeypatch.setattr(compute_request_module.requests, "Session", FakeSession)

    compiled = CompiledWorkflow("workflow-1", {"class": "Workflow", "inputs": {}, "outputs": {}, "steps": []}, {})
    request = ComputeRequest(compiled)
    submission = request.submit("http://example.test/compute", poll_interval_seconds=0, log_path=log_path)

    assert submission == ComputeSubmission(
        workflow_id="workflow-1",
        phase="RUNNING",
        accepted=True,
        submit_response={"ok": True},
        status_response={"status": "RUNNING"},
        logs={"log": "hello"},
    )
    assert submission.ok
    assert submission.exit_code == 0
    assert posted["url"] == "http://example.test/compute/"
    assert posted["data"]["id"] == "workflow-1"
    assert posted["headers"] == {"Content-Type": "application/json"}
    assert posted["get_urls"] == [
        "http://example.test/compute/workflow-1/status/",
        "http://example.test/compute/workflow-1/logs/",
    ]
    assert log_path.read_text(encoding="utf-8") == "{'log': 'hello'}"


@pytest.mark.fast
def test_compute_request_submit_requires_workflow_id() -> None:
    """A submission without a workflow id is refused before any request is made."""
    compiled = CompiledWorkflow("", {"class": "Workflow", "inputs": {}, "outputs": {}, "steps": []}, {})
    request = ComputeRequest(compiled)

    with pytest.raises(ValueError, match="requires workflow_id"):
        request.submit("http://example.test/compute")


@pytest.mark.fast
def test_workflow_compile_boundary_hides_compiler_info() -> None:
    """`compile()` hands back a `CompiledWorkflow` and nothing of the compiler.

    The typed compiler's internal result and artifact tree are not part of the
    public Python API.  This test pins the supported boundary, not retired
    implementation shapes.
    """
    emit_step = Step(_emit_text_tool(), step_name="emit_text")
    emit_step.inputs.message = "hello"
    workflow = Workflow([emit_step], "compile_boundary_demo")

    compiled = workflow.compile()

    assert isinstance(compiled, CompiledWorkflow)
    assert compiled.cwl_workflow["class"] == "Workflow"
    exposed = {field.name for field in dataclasses.fields(compiled)}
    assert exposed == {'name', 'cwl_workflow', 'cwl_job_inputs', 'lang_version', 'diagnostics'}, exposed


@pytest.mark.fast
def test_falsey_inline_values_are_preserved() -> None:
    """An empty string is a value, not an absent one.

    A truthiness test anywhere on this path would drop it silently."""
    echo = Step(clt_path=_adapter("echo"))
    echo.inputs.message = ""

    workflow_yaml = Workflow([echo], "wf").yaml
    assert workflow_yaml["steps"][0]["in"]["message"] == {
        "wic_inline_input": ""}


@pytest.mark.fast
def test_subworkflow_inputs_use_child_workflow_name_and_formal_parameters() -> None:
    """A subworkflow step names the child and passes its formal parameters.

    The child's own `inputs:` are declared, and the parent binds them by name,
    so the two documents agree about the interface between them."""
    touch = Step(clt_path=_adapter("touch"))
    touch.inputs.filename = "empty.txt"

    sub_step = Step(clt_path=_adapter("append"))
    subworkflow = Workflow([sub_step], "child")
    sub_step.inputs.file = subworkflow.inputs.file
    sub_step.inputs.str = subworkflow.inputs.str

    subworkflow.inputs.file = touch.outputs.file
    subworkflow.inputs.str = "Hello"

    root_yaml = Workflow([touch, subworkflow], "root").yaml
    subworkflow_step = root_yaml["steps"][1]

    assert subworkflow_step["id"] == "child.wic"
    assert subworkflow_step["in"] == {
        "file": {"wic_alias": "filechild"},
        "str": {"wic_inline_input": "Hello"},
    }
    assert "subtree" not in subworkflow_step
    assert subworkflow.yaml["inputs"] == {
        "file": {"type": "File"},
        "str": {"type": "string"},
    }
    assert subworkflow.yaml["steps"][0]["in"]["file"] == "file"
    assert subworkflow.yaml["steps"][0]["in"]["str"] == "str"


@pytest.mark.fast
def test_step_unknown_attribute_raises_immediately() -> None:
    """Binding an input the tool does not declare fails where it is written."""
    append = Step(clt_path=_adapter("append"))

    with pytest.raises(AttributeError, match="has no input named"):
        append.misspelled = "Hello"


@pytest.mark.fast
def test_incompatible_step_link_raises_invalid_link_error() -> None:
    """A link between incompatible types is refused at construction."""
    touch = Step(clt_path=_adapter("touch"))
    touch.inputs.filename = "empty.txt"
    append = Step(clt_path=_adapter("append"))

    with pytest.raises(InvalidLinkError, match="incompatible types"):
        append.inputs.str = touch.outputs.file


@pytest.mark.fast
@pytest.mark.parametrize('parameter_type, candidate_type, expected', [
    ('string', 'File', False),
    ('string', 'string', True),
    ('string[]', 'Any', True),
    ({'type': 'array', 'items': 'string'}, {'type': 'array', 'items': 'Any'}, True),
    ('string', {'type': 'record', 'fields': []}, True),
])
def test_python_api_uses_the_conservative_language_judgment(
        parameter_type: Any, candidate_type: Any, expected: bool) -> None:
    """The eager API rejects proven disjointness and defers every unknown."""
    assert _python_api_types_match(parameter_type, candidate_type) is expected


@pytest.mark.fast
def test_explicit_links_must_point_to_prior_steps_in_workflow_list() -> None:
    """A step may only consume what an earlier step produced.

    Order is meaning here: inference scans backwards, so a forward reference
    would describe a workflow that cannot run."""
    touch = Step(clt_path=_adapter("touch"))
    touch.inputs.filename = "empty.txt"

    append = Step(clt_path=_adapter("append"))
    append.inputs.file = touch.outputs.file
    append.inputs.str = "Hello"

    with pytest.raises(InvalidStepError, match="must appear earlier"):
        Workflow([append, touch], "wf").compile()


@pytest.mark.fast
def test_explicit_links_must_point_to_workflow_children() -> None:
    """A link may not reach a step outside the workflow that owns it."""
    external_touch = Step(clt_path=_adapter("touch"))
    external_touch.inputs.filename = "empty.txt"

    append = Step(clt_path=_adapter("append"))
    append.inputs.file = external_touch.outputs.file
    append.inputs.str = "Hello"

    with pytest.raises(InvalidStepError, match="not a child"):
        Workflow([append], "wf").compile()


@pytest.mark.fast
def test_scattering_over_two_ports_records_both_and_the_method() -> None:
    """`scatter_on` records every port it is given, and the method beside them.

    Named for what it asserts. `echo_3`'s ports are `string`, so nothing here
    exercises a CWL `Any`.
    """
    array_indices = Step(clt_path=_adapter("array_indices"))
    array_indices.inputs.input_array = ["hello world", "not", "what world?"]
    array_indices.inputs.input_indices = [0, 2]

    echo = Step(clt_path=_adapter("echo_3"))
    echo.inputs.message1 = array_indices.outputs.output_array
    echo.inputs.message2 = array_indices.outputs.output_array
    echo.inputs.message3 = "scalar"
    echo.scatter_on(
        echo.inputs.message1,
        echo.inputs.message2,
        method="flat_crossproduct",
    )

    workflow_yaml = Workflow([array_indices, echo], "wf").yaml
    assert workflow_yaml["steps"][1]["scatter"] == ["message1", "message2"]
    assert workflow_yaml["steps"][1]["scatterMethod"] == "flat_crossproduct"


@pytest.mark.fast
def test_compiled_workflow_writes_cwl_and_job_inputs(tmp_path: Path) -> None:
    """Writing produces two files, and their text matches the in-memory document."""
    compiled = CompiledWorkflow(
        "wf",
        {"class": "Workflow", "inputs": {}, "outputs": {}, "steps": []},
        {"message": "hello"},
    )

    cwl_path = compiled.write_cwl(tmp_path)
    inputs_path = compiled.write_job_inputs(tmp_path)

    assert cwl_path == tmp_path / "wf.cwl"
    assert inputs_path == tmp_path / "wf_inputs.yml"
    assert yaml.safe_load(compiled.to_cwl_yaml()) == compiled.cwl_workflow
    assert yaml.safe_load(compiled.to_job_inputs_yaml()) == compiled.cwl_job_inputs
    assert yaml.safe_load(cwl_path.read_text(encoding="utf-8")) == compiled.cwl_workflow
    assert yaml.safe_load(inputs_path.read_text(encoding="utf-8")) == compiled.cwl_job_inputs


@pytest.mark.fast
def test_port_names_reject_namespace_collisions() -> None:
    """A port may not shadow the port namespace's own API."""
    with pytest.raises(ValueError, match="reserved by port namespaces"):
        Step.from_cwl_document({'cwlVersion': 'v1.2', 'class': 'CommandLineTool', 'baseCommand': 'true',
                                'inputs': {'_store': 'string'}, 'outputs': {}}, process_name='bad')


@pytest.mark.fast
def test_workflow_write_wic_exports_source_workflow_with_inferred_edges(tmp_path: Path) -> None:
    """`write_wic` exports the source workflow, with inference still left to the compiler."""
    touch = Step(clt_path=_adapter("touch"))
    touch.inputs.filename = "empty.txt"

    append = Step(clt_path=_adapter("append"))
    append.inputs.str = "Hello"

    workflow = Workflow([touch, append], "linear_export")
    output_path = workflow.write_wic(tmp_path / "linear_export.wic")

    assert output_path == tmp_path / "linear_export.wic"
    exported = yaml.load(output_path.read_text(encoding="utf-8"), Loader=wic_loader())
    assert exported == workflow.yaml
    assert "file" not in exported["steps"][1]["in"]


@pytest.mark.fast
def test_workflow_to_wic_yaml_matches_export_text(tmp_path: Path) -> None:
    """The text written to disk is the text `to_wic_yaml` returns."""
    echo = Step(clt_path=_adapter("echo"))
    echo.inputs.message = "hello"
    workflow = Workflow([echo], "hello_export")

    output_path = workflow.write_wic(tmp_path)

    assert output_path == tmp_path / "hello_export.wic"
    assert output_path.read_text(encoding="utf-8") == workflow.to_wic_yaml()


@pytest.mark.fast
def test_workflow_write_wic_rejects_non_wic_file_extension(tmp_path: Path) -> None:
    """A destination must be a `.wic` file or a directory to put one in."""
    workflow = Workflow([], "wf")

    with pytest.raises(ValueError, match=r"\.wic file or a directory"):
        workflow.write_wic(tmp_path / "workflow.yaml")


@pytest.mark.fast
def test_compiled_artifact_writers_do_not_emit_intermediate_wic_files(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    """Writing the artifacts leaves no intermediate documents behind."""
    monkeypatch.chdir(tmp_path)
    echo = Step(clt_path=_adapter("echo"))
    echo.inputs.message = "hello"

    compiled = Workflow([echo], "hello_artifacts").compile()
    compiled.write_cwl(Path("autogenerated"))
    compiled.write_job_inputs(Path("autogenerated"))

    assert not list((tmp_path / "autogenerated").rglob("*.wic"))


@pytest.mark.fast
def test_workflow_outputs_are_serialized_with_type_and_source() -> None:
    """A workflow output carries its type and the step that produces it."""
    touch = Step(clt_path=_adapter("touch"))
    touch.inputs.filename = "empty.txt"

    append = Step(clt_path=_adapter("append"))
    append.inputs.file = touch.outputs.file
    append.inputs.str = "Hello"

    workflow = Workflow([touch, append], "wf")
    workflow.outputs.file = append.outputs.file

    workflow_yaml = workflow.yaml

    assert workflow_yaml["outputs"] == {
        "file": {"type": "File", "outputSource": "append/file"},
    }


@pytest.mark.fast
def test_config_yaml_normalizes_cwl_file_and_directory_objects(tmp_path: Path) -> None:
    """A `File` or `Directory` given as a config object reaches the step as its path."""
    input_dir = tmp_path / "input-dir"
    input_dir.mkdir()
    input_file = tmp_path / "input.txt"
    input_file.write_text("hello", encoding="utf-8")

    subdirectory_cfg = tmp_path / "subdirectory.yml"
    subdirectory_cfg.write_text(
        yaml.safe_dump(
            {
                "directory": {"class": "Directory", "location": str(input_dir)},
                "glob_pattern": ".",
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )
    subdirectory = Step(clt_path=_adapter("subdirectory"), config_path=subdirectory_cfg)
    assert subdirectory._as_workflow_step().input("directory") == \
        InlineLiteral(str(input_dir))

    append_cfg = tmp_path / "append.yml"
    append_cfg.write_text(
        yaml.safe_dump(
            {
                "file": {"class": "File", "location": str(input_file)},
                "str": "Hello",
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )
    append = Step(clt_path=_adapter("append"), config_path=append_cfg)
    assert append._as_workflow_step().input("file") == InlineLiteral(str(input_file))


@pytest.mark.fast
def test_config_file_without_location_is_a_structured_api_failure(tmp_path: Path) -> None:
    """A malformed CWL file value stays inside the one structured error family."""
    config = tmp_path / "append.yml"
    config.write_text("file:\n  class: File\n", encoding="utf-8")

    with pytest.raises(SophiosError) as caught:
        Step(clt_path=_adapter("append"), config_path=config)

    assert isinstance(caught.value, InvalidInputValueError)
    assert [diagnostic.code for diagnostic in caught.value.diagnostics] == [
        SophiosErrorCode.INVALID_INPUT_VALUE
    ]
    assert caught.value.diagnostics[0].message == "File value has no location or path"


@pytest.mark.fast
def test_scatter_rejects_unbound_foreign_or_scalar_inputs() -> None:
    """Scatter needs a bound, array-valued port belonging to the step itself.

    Three refusals, because each would otherwise produce a document that
    compiles and then fails at runtime for a different reason."""
    echo = Step(clt_path=_adapter("echo"))
    other_echo = Step(clt_path=_adapter("echo"))

    with pytest.raises(ValueError, match="bound before scattering"):
        echo.scatter = [echo.inputs.message]

    echo.inputs.message = "hello"
    with pytest.raises(ValueError, match="array-valued data"):
        echo.scatter = [echo.inputs.message]

    other_echo.inputs.message = ["a", "b"]
    with pytest.raises(ValueError, match="belong to the same step"):
        echo.scatter = [other_echo.inputs.message]


@pytest.mark.fast
def test_top_level_python_api_exposes_concrete_modules_only() -> None:
    """The package exposes modules, not re-exported names.

    A name re-exported at package level becomes a second import path for one
    thing, and the two drift."""
    assert hasattr(python_api_package, "workflow")
    assert hasattr(python_api_package, "tool_builder")
    assert not hasattr(python_api_package, "Step")
    assert not hasattr(python_api_package, "CommandLineTool")
    assert not hasattr(python_api_package, "CWL" + "BuilderValidationError")
    assert not hasattr(python_api_package, "WorkflowInputReference")
    assert not hasattr(python_api_package, "set_input_Step_Workflow")
    assert not hasattr(python_api_package, "extract_tools_paths_NONPORTABLE")


@pytest.mark.fast
def test_legacy_python_api_module_is_not_available() -> None:
    """The pre-rename module path is gone, not aliased."""
    with pytest.raises(ModuleNotFoundError):
        importlib.import_module("sophios.api.python.api")


@pytest.mark.fast
def test_run_local_subprocess_uses_explicit_env_without_global_mutation(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The runner is given its environment; the process environment is untouched.

    Mutating `os.environ` in a library changes behaviour for everything else
    embedding it, and outlives the call."""
    run_args = {
        "container_engine": "docker",
        "cwl_runner": "cwltool",
    }
    seen_env: dict[str, str] = {}
    sentinel_key = "SOPHIOS_TEST_SUBPROCESS_ENV"
    os.environ.pop(sentinel_key, None)

    def fake_run(cmd: list[str], check: bool, env: dict[str, str]) -> SimpleNamespace:
        del cmd, check
        seen_env.update(env)
        return SimpleNamespace(returncode=0)

    monkeypatch.setattr(run_local.sub, "run", fake_run)

    retval = run_local.run_local(
        run_args,
        True,
        passthrough_args=[],
        workflow_name="wf",
        basepath="autogenerated",
        user_env_vars={sentinel_key: "hello"},
    )

    assert retval == 0
    assert seen_env[sentinel_key] == "hello"
    assert sentinel_key not in os.environ


@pytest.mark.fast
def test_run_local_python_api_restores_environment_after_run(monkeypatch: pytest.MonkeyPatch) -> None:
    """Any environment a run needs is restored when the run ends."""
    run_args = {
        "container_engine": "docker",
        "cwl_runner": "cwltool",
    }
    sentinel_key = "SOPHIOS_TEST_PYAPI_ENV"
    os.environ.pop(sentinel_key, None)
    seen_inside: dict[str, str | None] = {"value": None}

    def fake_main(args: list[str]) -> int:
        del args
        seen_inside["value"] = os.environ.get(sentinel_key)
        return 0

    monkeypatch.setattr(run_local.cwltool.main, "main", fake_main)

    retval = run_local.run_local(
        run_args,
        False,
        passthrough_args=[],
        workflow_name="wf",
        basepath="autogenerated",
        user_env_vars={sentinel_key: "inside"},
    )

    assert retval == 0
    assert seen_inside["value"] == "inside"
    assert sentinel_key not in os.environ


@pytest.mark.fast
def test_run_local_deletes_nothing_in_the_working_directory(monkeypatch: pytest.MonkeyPatch,
                                                            tmp_path: Path) -> None:
    """A run used to `rmtree` every `<cachedir>*` beside it, and `--cachedir ''` matched the whole directory."""
    monkeypatch.chdir(tmp_path)
    (tmp_path / "cachedir_results").mkdir()
    (tmp_path / "notes.txt").write_text("mine", encoding="utf-8")
    monkeypatch.setattr(run_local.cwltool.main, "main", lambda args: 0)

    for cachedir in ("", "cachedir"):
        run_local.run_local({"container_engine": "docker", "cwl_runner": "cwltool", "cachedir": cachedir},
                            False, passthrough_args=[], workflow_name="wf", basepath="autogenerated")

    assert sorted(path.name for path in tmp_path.iterdir()) == ["cachedir_results", "notes.txt"]


@pytest.mark.fast
@pytest.mark.parametrize("cwl_runner", ["cwltool", "toil-cwl-runner"])
def test_build_cmd_uses_user_outdir(tmp_path: Path, cwl_runner: str) -> None:
    """A user-supplied `--outdir` is used once, and `--clean` follows the runner."""
    outdir = tmp_path / "workflow_output"

    cmd = run_local.build_cmd(
        "wf",
        str(tmp_path / "exec"),
        cwl_runner,
        "docker",
        passthrough_args=[],
        outdir=str(outdir),
    )

    assert cmd.count("--outdir") == 1
    assert cmd[cmd.index("--outdir") + 1] == str(outdir.resolve())
    if cwl_runner == "toil-cwl-runner":
        assert cmd[cmd.index("--clean") + 1] == "always"
    else:
        assert "--clean" not in cmd


@pytest.mark.fast
def test_build_cmd_is_quiet_unless_told_otherwise(tmp_path: Path) -> None:
    """`--quiet` is on for callers that say nothing and off when `quiet=False`, so `--debug` can be heard."""
    base = str(tmp_path / "exec")
    assert "--quiet" in run_local.build_cmd("wf", base, "cwltool", "docker", passthrough_args=[])
    assert "--quiet" not in run_local.build_cmd("wf", base, "cwltool", "docker", passthrough_args=[], quiet=False)
    toil_cmd = run_local.build_cmd("wf", base, "toil-cwl-runner", "docker", passthrough_args=[])
    assert "--quiet" not in toil_cmd


@pytest.mark.fast
@pytest.mark.parametrize(("run_args", "expected"), [({}, True), ({"quiet": "yes"}, True), ({"quiet": "no"}, False)])
def test_run_local_is_quiet_unless_told_otherwise(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    run_args: dict[str, str],
    expected: bool,
) -> None:
    """A caller that leaves `quiet` out of `run_args_dict` gets the `--quiet` it always got."""
    cmdlines: list[str] = []
    monkeypatch.setattr(run_local, "generate_run_script", cmdlines.append)
    run_local.run_local(
        {"cwl_runner": "cwltool", "container_engine": "docker", "generate_run_script": "yes", **run_args},
        False, passthrough_args=[], workflow_name="wf", basepath=str(tmp_path))
    assert ("--quiet" in cmdlines[0].split()) is expected


def _api_run_command(monkeypatch: pytest.MonkeyPatch, tmp_path: Path, run_args: dict[str, Any]) -> list[str]:
    """The runner command `Workflow.run()` builds for `run_args`, captured instead of executed."""
    touch = Step(clt_path=_adapter("touch"))
    touch.inputs.filename = "empty.txt"
    workflow = Workflow([touch], "quiet_demo")
    cmdlines: list[str] = []
    monkeypatch.setattr(python_runtime.pc, "verify_container_engine_config", lambda container, ignore: None)
    monkeypatch.setattr(python_runtime.pc, "cwl_docker_extract", lambda container, pull_dir, cwl_path: None)
    monkeypatch.setattr(python_runtime.rl, "generate_run_script", cmdlines.append)
    workflow.run(basepath=str(tmp_path), run_args_dict={"generate_run_script": "yes", **run_args})
    return cmdlines[0].split()


@pytest.mark.fast
def test_workflow_run_is_quiet_by_default(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    """The Python API has always run `cwltool` with `--quiet`, and still does unless told otherwise."""
    assert "--quiet" in _api_run_command(monkeypatch, tmp_path, {})


@pytest.mark.fast
@pytest.mark.parametrize(
    ("quiet", "expected"),
    [("yes", True), ("true", True), (True, True), ("no", False), ("false", False), (False, False)],
)
def test_workflow_run_quiet_run_arg(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    quiet: str | bool,
    expected: bool,
) -> None:
    """`run_args_dict={'quiet': ...}` switches `--quiet` and its value never reaches `cwltool` as a positional."""
    cmd = _api_run_command(monkeypatch, tmp_path, {"quiet": quiet})
    assert ("--quiet" in cmd) is expected
    assert not {"yes", "no", "true", "false", "True", "False"} & set(cmd)


@pytest.mark.fast
@pytest.mark.parametrize(("run_args", "expected"), [({}, True), ({"quiet": "yes"}, True), ({"quiet": "no"}, False)])
def test_run_cwl_workflow_is_quiet_unless_told_otherwise(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    run_args: dict[str, str],
    expected: bool,
) -> None:
    """The async runner was always quiet, and still is unless `quiet` is `no`."""
    cmdlines: list[str] = []
    monkeypatch.setattr(run_local_async, "generate_run_script", cmdlines.append)
    asyncio.run(run_local_async.run_cwl_workflow(
        "wf", str(tmp_path), "cwltool", "docker", {}, run_args_dict={"generate_run_script": "yes", **run_args}))
    assert ("--quiet" in cmdlines[0].split()) is expected


@pytest.mark.fast
def test_run_compute_does_not_apply_local_env(monkeypatch: pytest.MonkeyPatch) -> None:
    """A compute submission carries the workflow and its inputs, and no local environment."""
    submitted: dict[str, Any] = {}

    def fake_submit(
        request: ComputeRequest,
        submit_url: str,
        *,
        log_path: Path,
    ) -> ComputeSubmission:
        submitted["request"] = request
        submitted["submit_url"] = submit_url
        submitted["log_path"] = log_path
        return ComputeSubmission("wf", "RUNNING", True)

    def fail_temporary_env(user_env: dict[str, str]) -> Iterator[dict[str, str]]:
        del user_env
        raise AssertionError("run_compute must not apply local environment variables")

    monkeypatch.setattr(run_local, "_temporary_env", fail_temporary_env)
    monkeypatch.setattr(run_local.utils, "is_valid_url", lambda _url: True)
    monkeypatch.setattr(ComputeRequest, "submit", fake_submit)

    workflow: Json = {"class": "Workflow", "inputs": {}, "outputs": [], "steps": []}
    workflow_inputs: Json = {}

    assert run_local.run_compute("wf", workflow, workflow_inputs, "http://compute.test") == 0

    assert submitted["request"].cwl_workflow == workflow
    assert submitted["request"].cwl_job_inputs == workflow_inputs
    assert submitted["submit_url"] == "http://compute.test"
    assert str(submitted["log_path"]).startswith("compute_logs_wf__")


@pytest.mark.fast
def test_workflow_run_uses_basepath_for_docker_extract(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    """Container extraction is pointed at the basepath, not at the current directory."""
    example_path = REPO_ROOT / "examples" / "scripts" / "tool_builder_workflow.py"
    module = import_python_file(example_path.stem, example_path.resolve())
    workflow = module.build_workflow("hello from test")
    calls: dict[str, list[tuple[Any, ...]]] = {"verify": [], "extract": []}

    def fake_verify(container_engine: str, ignore_install: bool) -> None:
        calls["verify"].append((container_engine, ignore_install))

    def fake_extract(container_engine: str, pull_dir: str, cwl_path: Path) -> None:
        calls["extract"].append((container_engine, pull_dir, cwl_path))

    def fake_run_local(
        run_args_dict: dict[str, str],
        use_subprocess: bool,
        passthrough_args: list[str],
        workflow_name: str,
        basepath: str,
        user_env_vars: dict[str, str] | None = None,
        output_directories: dict[str, str] | None = None,
    ) -> int:
        del run_args_dict, use_subprocess, passthrough_args, workflow_name, basepath, user_env_vars, output_directories
        return 0

    monkeypatch.setattr(python_runtime.pc,
                        "verify_container_engine_config", fake_verify)
    monkeypatch.setattr(python_runtime.pc, "cwl_docker_extract", fake_extract)
    monkeypatch.setattr(python_runtime.rl, "run_local", fake_run_local)

    workflow.run(basepath=str(tmp_path))

    assert calls["verify"] == [("docker", False)]
    assert calls["extract"] == [
        ("docker", str(Path.cwd()), tmp_path / "tool_builder_workflow_demo.cwl")]


@pytest.mark.fast
def test_workflow_run_does_not_forward_python_run_flags_to_runner(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    """Flags meant for the Python API stay there; only runner flags pass through."""
    touch = Step(clt_path=_adapter("touch"))
    touch.inputs.filename = "empty.txt"
    workflow = Workflow([touch], "runtime_flag_demo")

    captured: dict[str, Any] = {}

    monkeypatch.setattr(
        python_runtime.pc,
        "verify_container_engine_config",
        lambda container, ignore: None,
    )
    monkeypatch.setattr(
        python_runtime.pc,
        "cwl_docker_extract",
        lambda container, pull_dir, cwl_path: None,
    )

    def fake_run_local(
        run_args_dict: dict[str, str],
        use_subprocess: bool,
        passthrough_args: list[str],
        workflow_name: str,
        basepath: str,
        user_env_vars: dict[str, str] | None = None,
        output_directories: dict[str, str] | None = None,
    ) -> int:
        captured["run_args_dict"] = run_args_dict
        captured["use_subprocess"] = use_subprocess
        captured["passthrough_args"] = passthrough_args
        captured["workflow_name"] = workflow_name
        captured["basepath"] = basepath
        captured["user_env_vars"] = user_env_vars
        return 0

    monkeypatch.setattr(python_runtime.rl, "run_local", fake_run_local)

    workflow.run(
        basepath=str(tmp_path),
        run_args_dict={
            "copy_output_files": "yes",
            "generate_run_script": "yes",
            "logLevel": "INFO",
            "outdir": str(tmp_path / "workflow_output"),
        },
    )

    assert captured["passthrough_args"] == ["--logLevel", "INFO"]
    assert captured["run_args_dict"]["copy_output_files"] == "yes"
    assert captured["run_args_dict"]["generate_run_script"] == "yes"
    assert captured["run_args_dict"]["outdir"] == str(tmp_path / "workflow_output")
    assert captured["workflow_name"] == "runtime_flag_demo"
    assert captured["basepath"] == str(tmp_path)


@pytest.mark.fast
def test_workflow_run_writes_virtual_output_directories_without_orphans(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    """A declared output directory is named in the inputs and not created early."""
    step = Step(clt_path=_output_directory_tool(tmp_path / "write_dir.cwl"))
    step.inputs.outDir = Path("result.outDir")
    workflow = Workflow([step], "virtual_run_demo")

    monkeypatch.setattr(python_runtime.pc, "verify_container_engine_config", lambda container, ignore: None)
    monkeypatch.setattr(python_runtime.pc, "cwl_docker_extract", lambda container, pull_dir, cwl_path: None)
    monkeypatch.setattr(
        python_runtime.rl,
        "run_local",
        lambda run_args_dict, use_subprocess, passthrough_args, workflow_name, basepath,
        user_env_vars=None, output_directories=None: 0,
    )

    workflow.run(basepath=str(tmp_path))

    inputs = yaml.safe_load((tmp_path / "virtual_run_demo_inputs.yml").read_text(encoding="utf-8"))
    assert inputs["virtual_run_demo__step__1__write_dir___outDir"] == "result.outDir"
    assert not (tmp_path / "result.outDir").exists()


@pytest.mark.fast
def test_async_serialized_run_uses_normalized_job_inputs(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    """The async path normalizes inputs the same way the direct path does."""
    workflow: Json = {
        "name": "async_virtual_demo",
        "class": "Workflow",
        "cwlVersion": "v1.2",
        "inputs": {"target": {"type": "Directory"}},
        "outputs": {},
        "steps": [
            {
                "id": "write_dir",
                "in": {"outDir": {"source": "target"}},
                "out": ["outDir"],
                "run": yaml.safe_load(_output_directory_tool(tmp_path / "write_dir.cwl").read_text(encoding="utf-8")),
            }
        ],
        "yaml_inputs": {
            "target": {
                "class": "Directory",
                "location": "async_result.outDir",
            }
        },
    }

    monkeypatch.setattr(run_local_async, "generate_run_script", lambda cmdline: None)

    retval = asyncio.run(
        run_local_async.run_cwl_serialized(
            workflow,
            str(tmp_path),
            "cwltool",
            "docker",
            {},
            run_args_dict={"generate_run_script": "yes"},
        )
    )

    inputs = yaml.safe_load((tmp_path / "async_virtual_demo_inputs.yml").read_text(encoding="utf-8"))
    assert retval == 0
    generated_cwl = yaml.safe_load((tmp_path / "async_virtual_demo.cwl").read_text(encoding="utf-8"))
    assert inputs["target"] == "async_result.outDir"
    assert generated_cwl["inputs"]["target"]["type"] == "string"
    assert generated_cwl["steps"][0]["run"]["inputs"]["outDir"]["type"] == "string"
    assert workflow["name"] == "async_virtual_demo"


@pytest.mark.fast
def test_compile_python_workflows() -> None:
    """Import and compile all auto-discovered Python workflow scripts."""
    from sophios.api.python import workflow  # pylint: disable=C0415:import-outside-toplevel

    global_config = _load_global_config()
    tools_cwl = sophios.plugins.get_tools_cwl(global_config)
    paths_tuples = _iter_python_workflow_paths(global_config)
    import_errors: list[str] = []
    generated_workflows: list[Path] = []
    for path_stem, path in paths_tuples:
        try:
            with _step_registry_injected(tools_cwl):
                module = import_python_file(path_stem, path)
                retval: workflow.Workflow = module.workflow()

            retval.compile()
            retval.write_wic(path.parent)
            generated_workflows.extend(
                path.parent / f"{wf.process_name}.wic" for wf in retval._flatten_subworkflows())

            config_ci = path.parent / "config_ci.json"
            json_contents = {}
            if config_ci.exists():
                with open(config_ci, mode="r", encoding="utf-8") as r:
                    json_contents = json.load(r)
            run_blacklist: list[str] = json_contents.get("run_blacklist", [])
            subworkflows: list[workflow.Workflow] = retval._flatten_subworkflows()[
                1:]
            run_blacklist += [wf.process_name for wf in subworkflows]
            json_contents["run_blacklist"] = run_blacklist
            with open(config_ci, mode="w", encoding="utf-8") as f:
                json.dump(json_contents, f)

        except Exception as exc:  # pylint: disable=W0718:broad-exception-caught
            import_errors.append(f"{path_stem}: {type(exc).__name__}: {exc}")
            traceback.print_exception(type(exc), value=exc, tb=None)
    if import_errors:
        pytest.fail("Python workflow imports failed:\n" +
                    "\n".join(import_errors))
    _write_manifest(generated_workflows)


@pytest.mark.fast
def test_validate_generated_python_workflows() -> None:
    """Every `.wic` the discovery step generated parses clean and validates
    against the exported schema."""
    if not PYTHON_WORKFLOW_MANIFEST.exists():
        pytest.fail(
            f"Missing generated workflow manifest: {PYTHON_WORKFLOW_MANIFEST}")

    validator = Draft202012Validator(wic_schema())
    workflow_paths = json.loads(
        PYTHON_WORKFLOW_MANIFEST.read_text(encoding="utf-8"))
    validation_errors: list[str] = []
    for workflow_path_str in workflow_paths:
        workflow_path = Path(workflow_path_str)
        parsed = parse(workflow_path.read_text(encoding="utf-8"), workflow_path.name)
        if not parsed.ok or parsed.document is None:
            validation_errors.extend(str(d) for d in parsed.diagnostics)
            continue
        validation_errors.extend(
            f"{workflow_path}: {error.message}"
            for error in validator.iter_errors(to_json(parsed.document)))

    if validation_errors:
        pytest.fail("Generated workflow validation failed:\n" +
                    "\n".join(validation_errors))


@pytest.mark.fast
def test_every_api_failure_is_catchable_as_one_type() -> None:
    """A caller writes one `except` and reads `.diagnostics`, whatever failed.

    The Python API used to raise two unrelated vocabularies: four bare
    `Exception` subclasses of its own, and `SophiosError` escaping from the
    compiler underneath. Neither was importable from anywhere a user of
    `Workflow.compile()` would look, which is what issue 111 is about -- the
    CLI has caught and reported this since it existed.
    """
    external = Step(clt_path=_adapter("touch"))
    external.inputs.filename = "empty.txt"
    append = Step(clt_path=_adapter("append"))
    append.inputs.file = external.outputs.file
    append.inputs.str = "Hello"

    with pytest.raises(SophiosError) as caught:
        Workflow([append], "wf").compile()

    assert isinstance(caught.value, InvalidStepError)
    assert [d.code for d in caught.value.diagnostics] == [SophiosErrorCode.INVALID_STEP]


@pytest.mark.fast
@pytest.mark.parametrize('error', [
    InvalidInputValueError, InvalidStepError, InvalidLinkError, InvalidCLTError])
def test_an_api_failure_carries_an_api_code_not_a_language_one(error: type[ApiError]) -> None:
    """`api0NN`, because the document is not what is wrong -- the call is.

    A `wic0NN` here would send a reader to a section of the language reference
    that does not describe their problem. `is_language` is the distinction, so
    a caller can route on it rather than on the string prefix.
    """
    raised = error('something the API could not do')
    code = raised.diagnostics[0].code
    assert code.value.startswith('api') and not code.is_language


def _detach_run_from_the_container_engine(monkeypatch: pytest.MonkeyPatch) -> None:
    """Keep a `Workflow.run()` call off the container engine and the disk."""
    monkeypatch.setattr(python_runtime.pc, 'verify_container_engine_config', lambda *_a, **_k: None)
    monkeypatch.setattr(python_runtime.pc, 'cwl_docker_extract', lambda *_a, **_k: None)
    monkeypatch.setattr(python_runtime.input_output, 'write_artifacts_to_disk', lambda *_a, **_k: None)


def _echo_workflow(name: str) -> Workflow:
    echo = Step(clt_path=_adapter('echo'))
    echo.inputs.message = 'hello'
    return Workflow([echo], name)


def _failed_run(monkeypatch: pytest.MonkeyPatch, exit_code: int) -> SophiosError:
    """The error `Workflow.run()` raises when the runner ends with `exit_code`."""
    _detach_run_from_the_container_engine(monkeypatch)
    monkeypatch.setattr(python_runtime.rl, 'run_local', lambda *_a, **_k: exit_code)
    with pytest.raises(SophiosError) as caught:
        _echo_workflow('failing').run()
    return caught.value


@pytest.mark.fast
def test_run_raises_workflow_run_error_on_a_failed_run(monkeypatch: pytest.MonkeyPatch) -> None:
    """`Workflow.run()` reports a failed run, with the runner's exit code, instead of returning."""
    raised = _failed_run(monkeypatch, 7)
    assert raised.diagnostics[0].code is SophiosErrorCode.WORKFLOW_RUN_FAILED
    assert "'failing'" in str(raised)
    from sophios.api.python.workflow import WorkflowRunError
    assert isinstance(raised, WorkflowRunError)
    assert raised.exit_code == 7


@pytest.mark.fast
@pytest.mark.parametrize('duplicate', [
    lambda error: pickle.loads(pickle.dumps(error)),
    copy.copy,
    copy.deepcopy,
], ids=['pickle', 'copy', 'deepcopy'])
def test_a_failed_run_error_survives_being_duplicated(monkeypatch: pytest.MonkeyPatch,
                                                      duplicate: Callable[[SophiosError], SophiosError]) -> None:
    """So it can come back from a worker process or be re-raised elsewhere with its exit code."""
    raised = _failed_run(monkeypatch, 7)
    clone = duplicate(raised)
    assert str(clone) == str(raised)
    assert list(clone.diagnostics) == list(raised.diagnostics)
    from sophios.api.python.workflow import WorkflowRunError
    assert isinstance(clone, WorkflowRunError)
    assert clone.exit_code == 7


@pytest.mark.fast
def test_run_does_not_raise_when_the_runner_succeeds(monkeypatch: pytest.MonkeyPatch) -> None:
    _detach_run_from_the_container_engine(monkeypatch)
    monkeypatch.setattr(python_runtime.rl, 'run_local', lambda *_a, **_k: 0)
    _echo_workflow('passing').run()


def _interrupted(_args: list[str]) -> int:
    """Stands in for a runner's `main` that the user stopped with Ctrl-C."""
    raise KeyboardInterrupt


@pytest.fixture(name='runner_child')
def _runner_child() -> Iterator[subprocess.Popen[str]]:
    """A process cwltool tracks as a child of its run.

    It exits once its stdin is closed, which is what cwltool does first when it terminates a child.
    """
    child = subprocess.Popen([sys.executable, '-c', 'import sys; sys.stdin.read()'], stdin=subprocess.PIPE, text=True)
    cwltool.utils.processes_to_kill.append(child)
    try:
        yield child
    finally:
        if child in cwltool.utils.processes_to_kill:
            cwltool.utils.processes_to_kill.remove(child)
        child.kill()
        child.wait()


@pytest.mark.fast
def test_an_interrupted_cwltool_run_terminates_the_runners_children_and_propagates(
        monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str],
        runner_child: subprocess.Popen[str]) -> None:
    monkeypatch.setattr(run_local.cwltool.main, 'main', _interrupted)
    with pytest.raises(KeyboardInterrupt):
        run_local.run_local({'container_engine': 'docker', 'cwl_runner': 'cwltool'}, False,
                            passthrough_args=[], workflow_name='wf', basepath='autogenerated')
    assert runner_child.wait(timeout=5) is not None
    assert 'terminated' in capsys.readouterr().err


@pytest.mark.fast
def test_an_interrupted_toil_run_propagates_and_claims_to_have_terminated_nothing(
        monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str],
        runner_child: subprocess.Popen[str]) -> None:
    """Toil tracks no children in cwltool, so nothing of cwltool's is touched and nothing is claimed."""
    monkeypatch.setattr(run_local.toil.cwl.cwltoil, 'main', _interrupted)
    with pytest.raises(KeyboardInterrupt):
        run_local.run_local({'container_engine': 'docker', 'cwl_runner': 'toil-cwl-runner'}, False,
                            passthrough_args=[], workflow_name='wf', basepath='autogenerated')
    assert runner_child.poll() is None
    assert 'terminated' not in capsys.readouterr().err


@pytest.mark.fast
def test_ctrl_c_during_run_is_not_reported_as_a_failed_run(monkeypatch: pytest.MonkeyPatch) -> None:
    """A loop that handles failed runs must still stop when the user presses Ctrl-C."""
    _detach_run_from_the_container_engine(monkeypatch)
    monkeypatch.setattr(run_local.cwltool.main, 'main', _interrupted)
    with pytest.raises(KeyboardInterrupt):
        _echo_workflow('interrupted').run()


@pytest.mark.fast
def test_a_failed_in_process_run_names_authored_steps(monkeypatch: pytest.MonkeyPatch, tmp_path: Path,
                                                      caplog: pytest.LogCaptureFixture,
                                                      capsys: pytest.CaptureFixture[str]) -> None:
    """cwltool names emitted ids; during the run they read as authored, and the failure points at the map."""
    import logging  # pylint: disable=import-outside-toplevel
    emitted = "wf__step__2__append"
    names_path = tmp_path / "wf.names.json"
    entry = {"id": emitted, "workflow": "wf", "index": 2,
             "name": "append", "inserted": False, "file": "wf.wic", "line": 7}
    names_path.write_text(json.dumps({"steps": {emitted: entry}, "ports": {}}), encoding="utf-8")

    def failing_main(args: list[str]) -> int:
        del args
        logging.getLogger("cwltool").error("[step %s] completed permanentFail", emitted)
        return 1

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(run_local.cwltool.main, "main", failing_main)
    caplog.set_level(logging.ERROR, logger="cwltool")

    retval = run_local.run_local({"container_engine": "docker", "cwl_runner": "cwltool"}, False,
                                 passthrough_args=[], workflow_name="wf", basepath=str(tmp_path))

    assert retval == 1
    assert f"[step 2 'append' ({emitted})] completed permanentFail" in caplog.messages
    assert f"Emitted ids are mapped to authored names in {names_path}" in capsys.readouterr().out
    assert not [f for f in logging.getLogger("cwltool").filters
                if isinstance(f, sophios.plugins.AuthoredNamesFilter)]


@pytest.mark.fast
@pytest.mark.parametrize('name', ['add_input', 'bind_input', 'bind_output', 'add_output'])
def test_the_string_keyed_workflow_methods_are_gone(name: str) -> None:
    """Workflow ports are declared and bound as objects, never by a name passed as text.

    The class is probed: on an instance, attribute sugar reads any name as a workflow input reference.
    """
    assert not hasattr(Workflow, name)


@pytest.mark.fast
@pytest.mark.parametrize('name', ['bind_input', 'get_output'])
def test_the_string_keyed_step_methods_are_gone(name: str) -> None:
    """Step ports are bound and read as objects, never by a name passed as text."""
    assert not hasattr(Step, name)
    assert not hasattr(Step(clt_path=_adapter('echo')), name)


@pytest.mark.fast
def test_a_renamed_step_writes_run_with_its_tool_stem(tmp_path: Path) -> None:
    """A step named apart from its tool names the tool file the bundle writes beside it."""
    first = Step(clt_path=_adapter('echo'), step_name='say_hi')
    first.inputs.message = 'hi'
    root = Workflow([first], 'renamed').write_wic(tmp_path)
    document = parse(root.read_text(encoding='utf-8'), root.name).document
    assert document is not None
    assert dict(document.steps[0].interpreted)['run'] == 'echo.cwl'
    assert (tmp_path / 'echo.cwl').is_file()
    assert '__step__' not in root.read_text(encoding='utf-8')


@pytest.mark.fast
def test_a_step_named_for_its_tool_writes_run_too() -> None:
    """Every step names its tool file, so the bundle compiles without the tool on a search path."""
    echo = Step(clt_path=_adapter('echo'))
    echo.inputs.message = 'hi'
    assert Workflow([echo], 'plain').yaml['steps'][0]['run'] == 'echo.cwl'


@pytest.mark.fast
def test_write_wic_leaves_the_tool_it_is_written_beside(tmp_path: Path) -> None:
    """Writing into the directory a step's own tool lives in does not rewrite that file."""
    source = tmp_path / 'echo.cwl'
    source.write_text(_adapter('echo').read_text(encoding='utf-8'), encoding='utf-8')
    before = source.read_bytes()
    echo = Step(clt_path=source)
    echo.inputs.message = 'hi'
    Workflow([echo], 'wf').write_wic(tmp_path)
    assert source.read_bytes() == before


@pytest.mark.fast
def test_write_wic_rejects_a_different_tool_under_the_same_stem(tmp_path: Path) -> None:
    """A different file already named `<stem>.cwl` is neither replaced nor trusted."""
    (tmp_path / 'echo.cwl').write_text('cwlVersion: v1.2\nclass: CommandLineTool\nbaseCommand: false\n'
                                       'inputs: {}\noutputs: {}\n', encoding='utf-8')
    echo = Step(clt_path=_adapter('echo'))
    echo.inputs.message = 'hi'
    with pytest.raises(InvalidStepError, match='already exists'):
        Workflow([echo], 'wf').write_wic(tmp_path)
    assert not (tmp_path / 'wf.wic').exists()


@pytest.mark.fast
def test_workflow_outputs_are_addressed_by_authored_step() -> None:
    """A workflow output names the step that produces it as the user named it."""
    touch = Step(clt_path=_adapter('touch'))
    touch.inputs.filename = 'empty.txt'
    append = Step(clt_path=_adapter('append'), step_name='add')
    append.inputs.file = touch.outputs.file
    append.inputs.str = 'Hello'
    wf = Workflow([touch, append], 'wf')
    wf.outputs.file = append.outputs.file
    assert wf.yaml['outputs']['file']['outputSource'] == 'add/file'


@pytest.mark.fast
def test_two_tools_sharing_a_file_stem_are_rejected(tmp_path: Path) -> None:
    """A document names a tool by its file stem, so two different tools under one stem are ambiguous."""
    def tool(command: str) -> dict[str, Any]:
        return {'cwlVersion': 'v1.2', 'class': 'CommandLineTool', 'baseCommand': command,
                'inputs': {}, 'outputs': {}}

    first = Step.from_cwl_document(tool('true'), process_name='first', run_path='tool.cwl')
    second = Step.from_cwl_document(tool('false'), process_name='second', run_path='tool.cwl')
    workflow = Workflow([first, second], 'shared_stem')

    with pytest.raises(InvalidStepError, match="share the file stem 'tool'"):
        workflow.write_wic(tmp_path)
    with pytest.raises(InvalidStepError, match="share the file stem 'tool'"):
        workflow.compile()


def _inner_and_sibling() -> tuple[Workflow, Step]:
    touch = Step(clt_path=_adapter('touch'))
    touch.inputs.filename = 'empty.txt'
    inner = Workflow([touch], 'inner')
    inner.outputs.made = touch.outputs.file
    cat = Step(clt_path=_adapter('cat'))
    cat.inputs.file = inner.outputs.made
    return inner, cat


@pytest.mark.fast
def test_a_sibling_step_consumes_a_subworkflows_output() -> None:
    """A nested workflow's output feeds a later sibling step, as a step's output does."""
    inner, cat = _inner_and_sibling()
    compiled = Workflow([inner, cat], 'outer').compile()
    cat_step = compiled.cwl_workflow['steps'][1]
    assert cat_step['in']['file'] == {'source': 'outer__step__1__inner.wic/made'}


@pytest.mark.fast
def test_a_parent_re_exports_a_subworkflows_output() -> None:
    """A parent workflow output may be backed by a nested workflow's output."""
    inner, cat = _inner_and_sibling()
    outer = Workflow([inner, cat], 'outer')
    outer.outputs.made = inner.outputs.made
    compiled = outer.compile()
    assert compiled.cwl_workflow['outputs']['made']['outputSource'] == 'outer__step__1__inner.wic/made'


@pytest.mark.fast
def test_a_workflow_cannot_consume_its_own_output() -> None:
    """One of a workflow's own steps reading that workflow's output is a cycle, refused by name."""
    touch = Step(clt_path=_adapter('touch'))
    touch.inputs.filename = 'empty.txt'
    cat = Step(clt_path=_adapter('cat'))
    wf = Workflow([touch, cat], 'loop')
    wf.outputs.made = touch.outputs.file
    cat.inputs.file = wf.outputs.made
    with pytest.raises(InvalidLinkError, match="own output"):
        wf.compile()


@pytest.mark.fast
def test_the_written_bundle_of_a_nested_workflow_compiles_to_the_same_cwl(tmp_path: Path) -> None:
    """The bundle `write_wic` writes for a nested workflow compiles to what the API compiles."""
    inner, cat = _inner_and_sibling()
    outer = Workflow([inner, cat], 'outer')
    direct = outer.compile().cwl_workflow
    root = outer.write_wic(tmp_path)
    assert parse(root.read_text(encoding='utf-8'), root.name).ok
    bundle = bundle_from_disk(root, {'global': {path.stem: path for path in tmp_path.glob('*.wic')}},
                              sophios.plugins.get_tools_cwl({'search_paths_cwl': {'global': [str(tmp_path)]}}))
    options, graph_settings, tag_paths = default_compilation_settings()
    result = sophios.compiler.compile_source(bundle, options, graph_settings, tag_paths,
                                             relative_run_path=True, testing=True,
                                             graph_target=get_graph_reps('outer'))
    assert normalize_artifact_cwl(inline_artifact_runs(result.artifact)) == direct


def _chain() -> tuple[Step, Step]:
    """`echo` over two messages feeding `cat`, bound before `echo` is scattered."""
    echo = Step(clt_path=_adapter('echo'))
    echo.inputs.message = ['a', 'b']
    cat = Step(clt_path=_adapter('cat'))
    cat.inputs.file = echo.outputs.stdout
    echo.scatter_on(echo.inputs.message)
    return echo, cat


@pytest.mark.fast
def test_a_step_scattered_after_binding_lifts_its_consumers_input() -> None:
    """The DSL compiles a chained scatter; the Python API refused it because the
    bound type was captured before `scatter_on` ran."""
    echo, cat = _chain()
    assert cat.inputs.file.effective_source_type() == {'type': 'array', 'items': 'File'}
    cat.scatter_on(cat.inputs.file)
    compiled = Workflow([echo, cat], 'chain').compile()
    steps = {s['id'].rsplit('__', 1)[-1]: s for s in compiled.cwl_workflow['steps']}
    assert steps['echo']['scatter'] == ['message'] and steps['cat']['scatter'] == ['file']


@pytest.mark.fast
def test_nested_crossproduct_lifts_one_level_per_scattered_port() -> None:
    """`nested_crossproduct` nests one array per scattered port; any other method adds one."""
    echo = Step(clt_path=_adapter('echo'))
    echo.inputs.message = 'a'
    first = Step(clt_path=_adapter('append'))
    first.inputs.file = echo.outputs.stdout
    first.inputs.str = ['x', 'y']
    sink = Step(clt_path=_adapter('cat'), step_name='sink')
    lifted = sink.inputs.file
    sink.inputs.file = first.outputs.file
    first.scatter_on(first.inputs.str, method='nested_crossproduct')
    assert lifted.effective_source_type() == {'type': 'array', 'items': 'File'}
    first.inputs.file = [{'class': 'File', 'location': 'p.txt'}, {'class': 'File', 'location': 'q.txt'}]
    first.scatter_on(first.inputs.file, first.inputs.str, method='nested_crossproduct')
    assert lifted.effective_source_type() == {
        'type': 'array', 'items': {'type': 'array', 'items': 'File'}}
    first.scatter_on(first.inputs.file, first.inputs.str, method='flat_crossproduct')
    assert lifted.effective_source_type() == {'type': 'array', 'items': 'File'}


@pytest.mark.fast
def test_a_subworkflows_output_is_not_lifted() -> None:
    """A nested workflow adds no array layer of its own: over an unscattered step its output stays `File`."""
    _inner, cat = _inner_and_sibling()
    assert cat.inputs.file.effective_source_type() == 'File'
    with pytest.raises(ValueError, match="array-valued data"):
        cat.scatter_on(cat.inputs.file)


@pytest.mark.fast
def test_a_scatter_inside_a_subworkflow_lifts_its_output() -> None:
    """A subworkflow output typed at bind time stayed `File` once its step was scattered,
    so a sibling could neither scatter over it nor consume it unscattered."""
    echo = Step(clt_path=_adapter('echo'))
    echo.inputs.message = ['a', 'b']
    inner = Workflow([echo], 'inner')
    inner.outputs.out = echo.outputs.stdout
    cat = Step(clt_path=_adapter('cat'))
    file = cat.inputs.file
    cat.inputs.file = inner.outputs.out
    echo.scatter_on(echo.inputs.message)
    assert file.effective_source_type() == {'type': 'array', 'items': 'File'}
    assert inner.yaml['outputs']['out']['type'] == {'type': 'array', 'items': 'File'}
    cat.scatter_on(file)
    compiled = Workflow([inner, cat], 'outer').compile()
    steps = {s['id'].rsplit('__', 1)[-1]: s for s in compiled.cwl_workflow['steps']}
    assert steps['cat']['scatter'] == ['file']


@pytest.mark.fast
def test_the_chained_scatter_agrees_with_the_dsl(tmp_path: Path) -> None:
    """The written bundle of a chained scatter compiles to what the API compiles."""
    echo, cat = _chain()
    cat.scatter_on(cat.inputs.file)
    wf = Workflow([echo, cat], 'chain')
    direct = wf.compile().cwl_workflow
    root = wf.write_wic(tmp_path)
    assert parse(root.read_text(encoding='utf-8'), root.name).ok
    bundle = bundle_from_disk(root, {'global': {path.stem: path for path in tmp_path.glob('*.wic')}},
                              sophios.plugins.get_tools_cwl({'search_paths_cwl': {'global': [str(tmp_path)]}}))
    options, graph_settings, tag_paths = default_compilation_settings()
    result = sophios.compiler.compile_source(bundle, options, graph_settings, tag_paths,
                                             relative_run_path=True, testing=True,
                                             graph_target=get_graph_reps('chain'))
    assert normalize_artifact_cwl(inline_artifact_runs(result.artifact)) == direct


def _merge() -> Workflow:
    """`a` and `b` each touch a file; `sink` takes both, merged into one list."""
    a = Step(clt_path=_adapter('touch'), step_name='a')
    a.inputs.filename = 'a.txt'
    b = Step(clt_path=_adapter('touch'), step_name='b')
    b.inputs.filename = 'b.txt'
    sink = Step.from_cwl_document({'cwlVersion': 'v1.2', 'class': 'CommandLineTool', 'baseCommand': 'true',
                                   'inputs': {'files': {'type': 'File[]'}}, 'outputs': {}}, process_name='sink')
    sink.inputs.files = StepInput(source=[a.outputs.file, b.outputs.file], link_merge='merge_flattened')
    return Workflow([a, b, sink], 'merge')


@pytest.mark.fast
def test_step_input_merges_two_sources() -> None:
    """Several sources and `linkMerge` on one step input, written from Python as objects."""
    compiled = _merge().compile()
    step = compiled.cwl_workflow['steps'][2]
    assert step['in']['files'] == {'source': ['merge__step__1__a/file', 'merge__step__2__b/file'],
                                   'linkMerge': 'merge_flattened'}
    assert 'MultipleInputFeatureRequirement' in compiled.cwl_workflow['requirements']


@pytest.mark.fast
def test_step_input_binds_an_undeclared_input_for_when() -> None:
    """A record may bind an input the tool does not declare, which `when:` then reads."""
    echo = Step(clt_path=_adapter('echo'))
    echo.inputs.message = 'hi'
    wf = Workflow([echo], 'guarded')
    echo.inputs.go = StepInput(source=wf.inputs.go)
    echo.when = '$(inputs.go)'
    compiled = wf.compile()
    assert compiled.cwl_workflow['steps'][0]['in']['go'] == {'source': 'go'}


@pytest.mark.fast
def test_only_a_step_input_binds_an_undeclared_input() -> None:
    """A plain value on a name the tool does not declare is still an unknown input."""
    echo = Step(clt_path=_adapter('echo'))
    with pytest.raises(AttributeError, match="no input named 'go'"):
        echo.inputs.go = True
    echo.inputs.go = StepInput(default=True)
    with pytest.raises(AttributeError, match="no input named 'go'"):
        echo.inputs.go = True


@pytest.mark.fast
def test_step_input_fields_are_written_in_cwl_spelling() -> None:
    """Every field but `source` is copied to the emitted step input as CWL spells it."""
    echo = Step(clt_path=_adapter('echo'))
    echo.inputs.message = StepInput(default=3, value_from='$(String(self + 1))', label='n')
    compiled = Workflow([echo], 'fields').compile()
    assert compiled.cwl_workflow['steps'][0]['in']['message'] == {
        'default': 3, 'valueFrom': '$(String(self + 1))', 'label': 'n'}


@pytest.mark.fast
@pytest.mark.parametrize('source', ['go', ['go']])
def test_a_string_is_never_a_step_input_source(source: Any) -> None:
    """A bare string is never a reference: sources are port objects."""
    with pytest.raises(InvalidInputValueError, match='str'):
        StepInput(source=source)


@pytest.mark.fast
def test_a_list_of_ports_is_never_a_literal() -> None:
    """A list of ports bound as a plain value was taken for a literal; it names `StepInput` instead."""
    a = Step(clt_path=_adapter('touch'))
    a.inputs.filename = 'a.txt'
    cat = Step(clt_path=_adapter('cat'))
    with pytest.raises(InvalidInputValueError, match='StepInput'):
        cat.inputs.file = [a.outputs.file]
    wf = Workflow([a, cat], 'listed')
    with pytest.raises(InvalidInputValueError, match='StepInput'):
        cat.inputs.file = (wf.inputs.f,)


@pytest.mark.fast
def test_a_merged_step_input_is_scatterable() -> None:
    """Merged sources arrive as one list, so the input they bind can be scattered."""
    wf = _merge()
    sink = cast(Step, wf.steps[2])
    sink.scatter_on(sink.inputs.files)
    assert wf.compile().cwl_workflow['steps'][2]['scatter'] == ['files']


@pytest.mark.fast
def test_a_step_input_is_checked_like_a_link() -> None:
    """A record's source must come from an earlier step, as a plain link's must."""
    a = Step(clt_path=_adapter('touch'))
    a.inputs.filename = 'a.txt'
    cat = Step(clt_path=_adapter('cat'))
    cat.inputs.file = StepInput(source=[a.outputs.file], pick_value='first_non_null')
    with pytest.raises(InvalidStepError, match='earlier in the workflow step list'):
        Workflow([cat, a], 'backwards').compile()


@pytest.mark.fast
def test_step_input_round_trips_through_write_wic(tmp_path: Path) -> None:
    """The written bundle carries the record and compiles to what the API compiles."""
    wf = _merge()
    direct = wf.compile().cwl_workflow
    root = wf.write_wic(tmp_path)
    parsed = parse(root.read_text(encoding='utf-8'), root.name)
    assert parsed.document is not None
    assert isinstance(parsed.document.steps[2].input('files'), CwlRecord)
    bundle = bundle_from_disk(root, {'global': {path.stem: path for path in tmp_path.glob('*.wic')}},
                              sophios.plugins.get_tools_cwl({'search_paths_cwl': {'global': [str(tmp_path)]}}))
    options, graph_settings, tag_paths = default_compilation_settings()
    result = sophios.compiler.compile_source(bundle, options, graph_settings, tag_paths,
                                             relative_run_path=True, testing=True,
                                             graph_target=get_graph_reps('merge'))
    assert normalize_artifact_cwl(inline_artifact_runs(result.artifact)) == direct


def _picked(pick_value: str) -> tuple[Workflow, Step]:
    """`a` and `b` each touch a file; `sink`, which takes one `File`, gets them through `pick_value`."""
    a = Step(clt_path=_adapter('touch'), step_name='a')
    a.inputs.filename = 'a.txt'
    b = Step(clt_path=_adapter('touch'), step_name='b')
    b.inputs.filename = 'b.txt'
    sink = Step.from_cwl_document({'cwlVersion': 'v1.2', 'class': 'CommandLineTool', 'baseCommand': 'true',
                                   'inputs': {'files': {'type': 'File'}}, 'outputs': {}}, process_name='sink')
    sink.inputs.files = StepInput(source=[a.outputs.file, b.outputs.file], pick_value=pick_value)
    return Workflow([a, b, sink], 'pick'), sink


@pytest.mark.fast
@pytest.mark.parametrize('pick_value', ['first_non_null', 'the_only_non_null'])
def test_a_picked_step_input_delivers_one_value(pick_value: str) -> None:
    """A `pickValue` that picks one of the sources delivers that one value, not a list to scatter."""
    _, sink = _picked(pick_value)
    with pytest.raises(ValueError, match='array-valued'):
        sink.scatter_on(sink.inputs.files)


@pytest.mark.fast
def test_all_non_null_still_delivers_a_list() -> None:
    """`all_non_null` keeps the list the sources make, so its input can be scattered."""
    wf, sink = _picked('all_non_null')
    sink.scatter_on(sink.inputs.files)
    assert wf.compile().cwl_workflow['steps'][2]['scatter'] == ['files']


@pytest.mark.fast
def test_a_step_input_and_a_plain_link_on_similarly_named_steps_compile() -> None:
    """A record's edges on step `sink` never take the name of a plain link to step `sink1`."""
    wf = _merge()
    c = Step(clt_path=_adapter('touch'), step_name='c')
    c.inputs.filename = 'c.txt'
    sink1 = Step.from_cwl_document({'cwlVersion': 'v1.2', 'class': 'CommandLineTool', 'baseCommand': 'true',
                                    'inputs': {'files': {'type': 'File'}}, 'outputs': {}}, process_name='sink1')
    sink1.inputs.files = c.outputs.file
    wf = Workflow([*wf.steps, c, sink1], 'similar')
    steps = wf.compile().cwl_workflow['steps']
    assert steps[4]['in']['files'] == {'source': 'similar__step__4__c/file'}


@pytest.mark.fast
@pytest.mark.parametrize('nest', [lambda port: [[port]], lambda port: {'x': port}, lambda port: [{'x': [port]}]])
def test_a_port_nested_in_a_literal_is_never_a_literal(nest: Any) -> None:
    """A port anywhere inside a list or mapping is refused, not passed through as a literal."""
    a = Step(clt_path=_adapter('touch'))
    a.inputs.filename = 'a.txt'
    cat = Step(clt_path=_adapter('cat'))
    with pytest.raises(InvalidInputValueError, match='StepInput'):
        cat.inputs.file = nest(a.outputs.file)


def _guard_and_message(record_first: bool) -> dict[str, Any]:
    """`wf.inputs.go` read by a record on an undeclared input and by a plain `string` input."""
    e1 = Step(clt_path=_adapter('echo'), step_name='e1')
    e1.inputs.message = 'hi'
    e2 = Step(clt_path=_adapter('echo'), step_name='e2')
    wf = Workflow([e1, e2], 'order')
    if record_first:
        e1.inputs.go = StepInput(source=wf.inputs.go)
        e2.inputs.message = wf.inputs.go
    else:
        e2.inputs.message = wf.inputs.go
        e1.inputs.go = StepInput(source=wf.inputs.go)
    e1.when = '$(inputs.go)'
    return cast(dict[str, Any], wf.compile().cwl_workflow['inputs'])


@pytest.mark.fast
def test_a_record_on_an_undeclared_input_does_not_type_the_workflow_input() -> None:
    """The workflow input's type does not depend on which binding came first."""
    assert _guard_and_message(True)['go']['type'] == _guard_and_message(False)['go']['type'] == 'string'


@pytest.mark.fast
def test_a_workflow_input_only_a_transforming_record_reads_is_any() -> None:
    """A workflow input read only through a `valueFrom` has no type to borrow, so it is `Any`."""
    echo = Step(clt_path=_adapter('echo'))
    wf = Workflow([echo], 'transformed')
    echo.inputs.message = StepInput(source=wf.inputs.n, value_from='$(String(self))')
    assert wf.compile().cwl_workflow['inputs']['n']['type'] == 'Any'
