"""A plain CWL workflow passes through `--allow_raw_cwl` as it is.

With the flag, a `--yaml` file whose top level says `cwlVersion` and
`class: Workflow` (or packs a `main` Workflow in `$graph`), and that has no
Sophios syntax, is not compiled: the runner is given the file itself and
`--inputs_file` as its job. Everything else takes the compile path unchanged.
"""
import io
import json
from pathlib import Path
from typing import Any, Callable

import pytest
import yaml

import sophios.main as cli
import sophios.post_compile as pc

#: Twelve plain Workflows of the CWL v1.2 conformance suite; see its README.md.
CONFORMANCE = Path(__file__).resolve().parent / 'data' / 'cwl-v1.2'
CASES = yaml.safe_load((CONFORMANCE / 'cases.yaml').read_text(encoding='utf-8'))

PLAIN = '''cwlVersion: v1.2
class: Workflow
inputs:
  message: string
outputs:
  copied:
    type: File
    outputSource: copy/copied
steps:
  say:
    run: say.cwl
    in:
      message: message
    out: [said]
  copy:
    run: copy.cwl
    in:
      text: say/said
    out: [copied]
'''

SAY = '''cwlVersion: v1.2
class: CommandLineTool
baseCommand: echo
inputs:
  message:
    type: string
    inputBinding: {position: 1}
stdout: said.txt
outputs:
  said: stdout
'''

COPY = '''cwlVersion: v1.2
class: CommandLineTool
baseCommand: cat
inputs:
  text:
    type: File
    inputBinding: {position: 1}
stdout: copied.txt
outputs:
  copied: stdout
'''

PACKED = '''cwlVersion: v1.2
$graph:
- id: say
  class: CommandLineTool
  baseCommand: echo
  inputs: {message: {type: string, inputBinding: {position: 1}}}
  stdout: said.txt
  outputs: {said: stdout}
- id: {main}
  class: Workflow
  inputs: {message: string}
  outputs: {said: {type: File, outputSource: say/said}}
  steps:
    say: {run: '#say', in: {message: message}, out: [said]}
'''

LIST_STEPS = PLAIN.replace('''steps:
  say:
    run: say.cwl
    in:
      message: message
    out: [said]
  copy:
    run: copy.cwl
''', '''steps:
- id: say
  run: say.cwl
  in:
    message: message
  out: [said]
- id: copy
  run: copy.cwl
''').replace('''    in:
      text: say/said
    out: [copied]
''', '''  in:
    text: say/said
  out: [copied]
''')


class _Compiled(BaseException):
    """Raised where the compile path starts: reading the config.

    Not an `Exception`, so that `main()`'s arm for unexpected failures lets it through.
    """


@pytest.fixture(name='compile_path')
def _compile_path(monkeypatch: pytest.MonkeyPatch) -> None:
    """The compile path raises `_Compiled` instead of compiling."""
    def compiled(*_args: object, **_kwargs: object) -> None:
        raise _Compiled
    monkeypatch.setattr(cli.io, 'get_config', compiled)


@pytest.fixture(name='sophios')
def _sophios(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> Callable[..., Path]:
    """Run the CLI from `tmp_path/cwd` on a document written to `tmp_path/wf/<name>`, or on a path.

    What would reach for a container engine is recorded instead.
    """
    monkeypatch.setattr(pc, 'verify_container_engine_config', lambda *_a, **_k: None)
    extracted: list[Path] = []
    monkeypatch.setattr(pc, 'cwl_docker_extract', lambda _engine, _pull, path: extracted.append(Path(path)))
    (tmp_path / 'wf').mkdir()
    (tmp_path / 'wf' / 'say.cwl').write_text(SAY, encoding='utf-8')
    (tmp_path / 'wf' / 'copy.cwl').write_text(COPY, encoding='utf-8')
    (tmp_path / 'jobs').mkdir()
    (tmp_path / 'jobs' / 'job.yml').write_text('message: hello\n', encoding='utf-8')
    (tmp_path / 'cwd').mkdir()
    monkeypatch.chdir(tmp_path / 'cwd')

    def run(text: str | Path, *flags: str, name: str = 'plain.cwl') -> Path:
        if isinstance(text, Path):
            workflow = text
        else:
            workflow = tmp_path / 'wf' / name
            workflow.write_text(text, encoding='utf-8')
        monkeypatch.setattr('sys.argv', ['sophios', '--yaml', str(workflow), *flags])
        cli.main()
        assert extracted in ([], [workflow])
        return workflow
    return run


@pytest.mark.fast
@pytest.mark.parametrize('text', [PLAIN, LIST_STEPS, PACKED.replace('{main}', 'main'),
                                  PACKED.replace('{main}', "'#main'")],
                         ids=['steps-map', 'steps-list', 'packed-main', 'packed-hash-main'])
def test_a_plain_cwl_workflow_is_its_own_artifact(sophios: Callable[..., Path], text: str,
                                                  capsys: pytest.CaptureFixture[str]) -> None:
    """Nothing is compiled or written: the file itself is what a run would use."""
    workflow = sophios(text, '--allow_raw_cwl', '--generate_cwl_workflow')
    assert workflow.read_text(encoding='utf-8') == text
    assert not Path('autogenerated').exists()
    assert f'{workflow} is a CWL workflow' in capsys.readouterr().out


@pytest.mark.fast
@pytest.mark.parametrize(('text', 'name'), [
    (PLAIN.replace('message: message', 'message: !ii hello'), 'plain.cwl'),
    ('wic:\n  graphviz:\n    label: x\n' + PLAIN, 'plain.cwl'),
    (PLAIN.replace('cwlVersion: v1.2\n', ''), 'plain.cwl'),
    (SAY, 'say_root.cwl'),
    (PACKED.replace('{main}', 'main').replace('class: Workflow', 'class: CommandLineTool'), 'plain.cwl'),
    ('steps:\n- id: say\n', 'plain.wic'),
], ids=['sophios-tag', 'wic-sidecar', 'no-cwlVersion', 'a-tool', 'packed-tool', 'a-wic-document'])
@pytest.mark.usefixtures('compile_path')
def test_anything_else_is_compiled_as_before(sophios: Callable[..., Path], text: str, name: str) -> None:
    """Sophios syntax, a tool, a packed tool or a missing `cwlVersion` keeps the compile path."""
    with pytest.raises(_Compiled):
        sophios(text, '--allow_raw_cwl', '--generate_cwl_workflow', name=name)


@pytest.mark.fast
@pytest.mark.usefixtures('compile_path')
def test_without_allow_raw_cwl_a_plain_cwl_workflow_is_compiled_as_before(sophios: Callable[..., Path]) -> None:
    """Without the flag a plain CWL workflow is not a Sophios exception: it is compiled as today."""
    with pytest.raises(_Compiled):
        sophios(PLAIN, '--generate_cwl_workflow')


@pytest.mark.fast
def test_run_sh_gives_the_runner_the_workflow_and_the_job_as_they_are(sophios: Callable[..., Path],
                                                                      tmp_path: Path) -> None:
    """Both paths are the files given, not copies under autogenerated/."""
    job = tmp_path / 'jobs' / 'job.yml'
    workflow = sophios(PLAIN, '--allow_raw_cwl', '--generate_run_script', '--inputs_file', str(job))
    command = Path('run.sh').read_text(encoding='utf-8').split()
    assert command[-2:] == [str(workflow), str(job)]
    assert not list(Path('autogenerated').glob('*.cwl'))


@pytest.mark.fast
def test_without_inputs_file_the_runner_gets_no_job_file(sophios: Callable[..., Path]) -> None:
    """The workflow's own defaults apply; the runner names any required input left unset."""
    workflow = sophios(PLAIN, '--allow_raw_cwl', '--generate_run_script')
    assert Path('run.sh').read_text(encoding='utf-8').split()[-1] == str(workflow)


@pytest.mark.fast
@pytest.mark.parametrize('flag', ['--cwl_inline_runtag', '--cwl_inline_subworkflows', '--partial_failure_enable',
                                  '--docker_remove_entrypoints'])
def test_a_flag_that_rewrites_compiled_cwl_is_an_error_for_a_plain_cwl_workflow(
        sophios: Callable[..., Path], flag: str, capsys: pytest.CaptureFixture[str]) -> None:
    """There is no compiled CWL to rewrite, so the flag is refused rather than ignored."""
    with pytest.raises(SystemExit) as caught:
        sophios(PLAIN, '--allow_raw_cwl', '--generate_run_script', flag)
    assert caught.value.code == 2
    assert flag in capsys.readouterr().err
    assert not Path('run.sh').exists()


@pytest.mark.fast
def test_graphviz_draws_the_plain_cwl_workflow_with_cwltool(sophios: Callable[..., Path],
                                                            monkeypatch: pytest.MonkeyPatch) -> None:
    """cwltool draws the file itself; there is no compiled graph for Sophios to draw."""
    commands: list[str] = []
    monkeypatch.setattr(cli.shutil, 'which', lambda _name: '/usr/bin/dot')
    monkeypatch.setattr(cli.sub, 'run', lambda command, **_k: commands.append(command))
    workflow = sophios(PLAIN, '--allow_raw_cwl', '--generate_cwl_workflow', '--graphviz')
    assert commands == [f'cwltool_filterlog --print-dot {workflow} | dot -Tsvg > autogenerated/plain.svg']


@pytest.mark.fast
def test_a_plain_cwl_workflow_does_not_run_the_analyses_of_a_workflow_of_the_same_name(
        sophios: Callable[..., Path], monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]) -> None:
    """A `plain.wic` compiled earlier left its real-time analyses beside its CWL; `plain.cwl` is not that workflow."""
    Path('autogenerated').mkdir()
    Path('autogenerated/plain.realtime.json').write_text(json.dumps([{
        'name': 'plain', 'analysis': 'count', 'file_pattern': '*.txt', 'max_times': 2, 'interval': 60,
        'cwl': 'realtime/plain/count_only.cwl', 'inputs': 'realtime/plain/count_only_inputs.yml',
        'root_dir': str(Path.cwd()), 'declared_at': 'plain.wic:3:3'}]), encoding='utf-8')
    given: list[tuple[Any, ...]] = []

    def run_local(run_args_dict: dict[str, str], *_args: Any, realtime_plans: tuple[Any, ...] = (),
                  **_kwargs: Any) -> int:
        given.append((run_args_dict['cachedir'], realtime_plans))
        return 0
    monkeypatch.setattr(cli.run_local, 'run_local', run_local)

    sophios(PLAIN, '--allow_raw_cwl', '--run_local')

    assert given == [('', ())]
    assert 'eal-time analysis' not in capsys.readouterr().out


@pytest.mark.needs_cwltool
def test_a_plain_cwl_workflow_runs_as_it_is(sophios: Callable[..., Path], tmp_path: Path) -> None:
    """The run is cwltool's run of the file: `say/said` reaches `copy` because nothing renamed `say`."""
    workflow = sophios(PLAIN, '--allow_raw_cwl', '--run_local', '--inputs_file', str(tmp_path / 'jobs' / 'job.yml'))
    summary = json.loads(Path('autogenerated/output_plain.json').read_text(encoding='utf-8'))
    assert Path(summary['copied']['path']).read_text(encoding='utf-8') == 'hello\n'
    assert workflow.read_text(encoding='utf-8') == PLAIN
    assert not Path('autogenerated/plain.cwl').exists()


def _portable(value: Any) -> Any:
    """`value` without `location` and `path`, which name the directory a run wrote to."""
    if isinstance(value, dict):
        return {key: _portable(item) for key, item in value.items() if key not in ('location', 'path')}
    if isinstance(value, list):
        return [_portable(item) for item in value]
    return value


@pytest.mark.needs_cwltool
@pytest.mark.parametrize('case', CASES, ids=[case['id'] for case in CASES])
def test_a_conformance_workflow_runs_through_sophios_as_cwltool_runs_it(
        sophios: Callable[..., Path], case: dict[str, str], tmp_path: Path) -> None:
    """The output object is cwltool's own for the same file and job."""
    import cwltool.main  # pylint: disable=import-outside-toplevel
    workflow, job = CONFORMANCE / case['tool'], CONFORMANCE / case['job']
    direct = io.StringIO()
    assert cwltool.main.main(['--quiet', '--outdir', str(tmp_path / 'direct'), str(workflow), str(job)],
                             stdout=direct) == 0
    sophios(workflow, '--allow_raw_cwl', '--run_local', '--inputs_file', str(job))
    summary = json.loads(Path(f'autogenerated/output_{workflow.stem}.json').read_text(encoding='utf-8'))
    assert _portable(summary) == _portable(json.loads(direct.getvalue()))
