"""The discovery config: a file the user names is only read; the default is generated once."""
from pathlib import Path

import pytest

from sophios import input_output as io
from sophios import main as cli


@pytest.mark.fast
def test_a_config_file_that_does_not_exist_leaves_the_users_config_alone(
        monkeypatch: pytest.MonkeyPatch, tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """A typo in --config_file used to write a fresh default config over the user's own."""
    monkeypatch.setenv('HOME', str(tmp_path))
    monkeypatch.chdir(tmp_path)
    users_config = tmp_path / 'wic' / 'global_config.json'
    users_config.parent.mkdir()
    users_config.write_text('{"mine": true}', encoding='utf-8')
    (tmp_path / 'w.wic').write_text('steps:\n  touch:\n', encoding='utf-8')
    monkeypatch.setattr('sys.argv', ['sophios', '--yaml', 'w.wic', '--generate_cwl_workflow',
                                     '--homedir', str(tmp_path), '--config_file', 'typo.json'])

    with pytest.raises(SystemExit) as caught:
        cli.main()

    assert caught.value.code == 2
    assert 'typo.json' in capsys.readouterr().err
    assert users_config.read_text(encoding='utf-8') == '{"mine": true}'


@pytest.mark.fast
def test_the_default_config_is_generated_under_homedir_once_then_only_read(
        monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    """Without --config_file, the first run writes the default; after that, the user's edits are what is read."""
    monkeypatch.setenv('HOME', str(tmp_path / 'home'))
    homedir = tmp_path / 'homedir'

    generated = io.get_config(None, homedir)

    default = io.default_config_file(homedir)
    assert io.read_config_from_disk(default) == generated
    default.write_text('{"search_paths_cwl": {}, "search_paths_wic": {}}', encoding='utf-8')
    assert io.get_config(None, homedir) == {'search_paths_cwl': {}, 'search_paths_wic': {}}


@pytest.mark.fast
@pytest.mark.parametrize('generate_explicitly', [False, True], ids=['first-use', 'generate-config'])
@pytest.mark.parametrize('relative_homedir', [False, True], ids=['absolute-home', 'relative-home'])
def test_cli_provisions_the_selected_home_without_touching_an_existing_installation(
        monkeypatch: pytest.MonkeyPatch, tmp_path: Path,
        generate_explicitly: bool, relative_homedir: bool) -> None:
    """The config, adapters and examples all belong to --homedir, not the process home."""
    process_home = tmp_path / 'process-home'
    monkeypatch.setattr(Path, 'home', classmethod(lambda cls: process_home))
    monkeypatch.chdir(tmp_path)
    io.get_config(None, process_home)
    before = {path.relative_to(process_home): path.read_bytes()
              for path in process_home.rglob('*') if path.is_file()}
    homedir = Path('selected-home') if relative_homedir else tmp_path / 'selected-home'
    argv = ['sophios', '--homedir', str(homedir)]
    if generate_explicitly:
        argv += ['--generate_config']
    else:
        (tmp_path / 'w.wic').write_text(
            'steps:\n  - id: touch\n    in:\n      filename: !ii empty.txt\n', encoding='utf-8')
        argv += ['--yaml', 'w.wic', '--generate_cwl_workflow']
    monkeypatch.setattr('sys.argv', argv)

    if generate_explicitly:
        with pytest.raises(SystemExit) as caught:
            cli.main()
        assert caught.value.code == 0
    else:
        cli.main()
        assert (tmp_path / 'autogenerated' / 'w.cwl').is_file()

    config = io.read_config_from_disk(io.default_config_file(homedir))
    adapters = homedir.absolute() / 'wic' / 'cwl_adapters'
    examples = homedir.absolute() / 'wic' / 'examples'
    assert config['search_paths_cwl']['global'] == [str(adapters)]
    assert config['search_paths_wic']['global'] == [str(examples)]
    assert (adapters / 'touch.cwl').is_file()
    assert any(examples.rglob('*.wic'))
    assert {path.relative_to(process_home): path.read_bytes()
            for path in process_home.rglob('*') if path.is_file()} == before


@pytest.mark.fast
def test_explicit_config_paths_stay_relative_to_cwd_without_provisioning(
        monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    """An explicit config keeps its path semantics and does not create a default installation."""
    monkeypatch.chdir(tmp_path)
    config_file = tmp_path / 'config' / 'custom.json'
    absolute_examples = tmp_path / 'absolute-examples'
    io.write_config_to_disk({
        'search_paths_cwl': {'global': ['relative-adapters']},
        'search_paths_wic': {'global': [str(absolute_examples)]},
    }, config_file)
    before = config_file.read_bytes()
    homedir = tmp_path / 'unused-home'

    config = io.get_config(config_file, homedir)

    assert config['search_paths_cwl']['global'] == [str(tmp_path / 'relative-adapters')]
    assert config['search_paths_wic']['global'] == [str(absolute_examples)]
    assert config_file.read_bytes() == before
    assert not homedir.exists()
    assert not (tmp_path / 'relative-adapters').exists()
    assert not absolute_examples.exists()


@pytest.mark.fast
def test_basic_config_defaults_to_process_home_without_writing(
        monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    """Read-only discovery callers can still ask for the default paths without provisioning them."""
    process_home = tmp_path / 'process-home'
    monkeypatch.setattr(Path, 'home', classmethod(lambda cls: process_home))

    config = io.get_basic_config()

    assert config['search_paths_cwl']['global'] == [str(process_home / 'wic' / 'cwl_adapters')]
    assert config['search_paths_wic']['global'] == [str(process_home / 'wic' / 'examples')]
    assert not process_home.exists()
