from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import pytest

import sophios
import sophios.cli
import sophios.input_output as io
import sophios.plugins
import sophios.api
import sophios.api.python.workflow
from sophios.lang import parse
from sophios.wic_types import Json, Tools


@dataclass(frozen=True, slots=True)
class CorpusRegistry:
    """The explicit environment-dependent inputs used by corpus tests."""

    tools: Tools
    workflows: dict[str, dict[str, Path]]


def _config() -> tuple[Json, bool]:
    """Read configuration without provisioning a missing user config."""
    args = sophios.cli.get_args()
    config_file = args.config_file or io.default_config_file(Path(args.homedir))
    if config_file.exists():
        return io.read_config_from_disk(config_file), args.quiet
    return io.get_basic_config(), args.quiet


@lru_cache(maxsize=1)
def workflow_paths() -> dict[str, dict[str, Path]]:
    """Discover workflow source paths without loading any process plugins."""
    config, _ = _config()
    paths: dict[str, dict[str, Path]] = sophios.plugins.get_yml_paths(config)
    return paths


def yml_path_is_workflow(yml_path: Path) -> bool:
    """Return whether a `.wic` file looks like a compilable workflow root.

    Args:
        yml_path (Path): Path to a workflow-definition file.

    Returns:
        bool: True when the file declares steps or workflow implementations.
    """
    # parse() rather than read_wic(): a corpus file may carry diagnostics and
    # still be a document whose shape answers the question.
    document = parse(yml_path.read_text(encoding='utf-8'), str(yml_path)).document
    if document is None:
        return False
    return (
        bool(document.steps) or document.steps_as_mapping
        or 'implementations' in dict(document.passthrough)
        or (document.sidecar is not None and 'implementations' in dict(document.sidecar.entries))
    )


@lru_cache(maxsize=1)
def load_test_registry() -> CorpusRegistry:
    """Discover tools and workflows on first test execution, never at collection.

    Importing this module therefore cannot discover CWL plugins or write under
    ``autogenerated/``.
    """
    config, quiet = _config()
    return CorpusRegistry(sophios.plugins.get_tools_cwl(config, quiet=quiet), workflow_paths())


@pytest.fixture(scope='session')
def corpus_registry() -> CorpusRegistry:
    """Explicit registry fixture for tests that exercise the discovered corpus."""
    return load_test_registry()
