# IMPORTANT: Use .. for the Build Context https://docs.docker.com/build/building/context/
# i.e. `sudo docker build ... -f Dockerfile ..`
FROM fedora

# Install conda / mamba
RUN dnf update -y && dnf install -y wget awk

ARG CONDA="Miniforge3-Linux-x86_64.sh"

RUN wget --quiet https://github.com/conda-forge/miniforge/releases/latest/download/$CONDA && \
    chmod +x $CONDA && \
    ./$CONDA -b -p /miniforge && \
    rm -f $CONDA
ENV PATH=/miniforge/bin:$PATH

# Install sophios
RUN dnf install -y git

COPY . /sophios
WORKDIR /sophios

#RUN conda create --name wic
#RUN conda activate wic
# The above command prints
# CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
# It still prints that even if we run `conda init bash` first.
# But this is a Docker image; we don't necessarily need to additionally isolate
# wic within a conda environment. Let's just install it globally!
RUN mamba env update --name base --file install/system_deps.yml
RUN pip install -e ".[all_except_runner_src]"

RUN mamba clean --all --yes
RUN pip cache purge
RUN dnf clean all

ADD docker/Dockerfile_fedora .
