#!/bin/bash
# Install the built wheel and the built sdist, each into a fresh virtual
# environment, and use each install the way a user does: from a directory
# outside the checkout, with the config, adapters and tutorials the package
# ships. A wheel missing its package data, or an sdist that cannot build, fails
# here instead of on PyPI.
#   check.sh <dist dir> <version>
# <dist dir> holds exactly one sophios wheel and one sophios sdist; <version> is
# what every install must report, as verify-version resolved it.
set -euo pipefail

dist=$(cd "$1" && pwd)
expected=$2

one_file() {
    # The one file in $dist matching $2, or an error naming what $1 found.
    local found
    found=$(find "$dist" -maxdepth 1 -name "$2")
    if [ "$(printf '%s\n' "$found" | wc -l)" -ne 1 ] || [ ! -f "$found" ]; then
        echo "ERROR: expected one $1 in $dist, found: ${found:-nothing}" >&2
        exit 1
    fi
    echo "$found"
}
wheel=$(one_file wheel 'sophios-*.whl')
sdist=$(one_file sdist 'sophios-*.tar.gz')

# Nothing from the checkout may reach the installs.
unset PYTHONPATH

for artifact in "$wheel" "$sdist"; do
    echo "::group::$(basename "$artifact")"
    work=$(mktemp -d)
    mkdir "$work/build-home" "$work/home" "$work/run"
    python -m venv "$work/venv"

    # setup.py writes a config under HOME while it builds (the sdist builds
    # here); that must not land in the home the install is then used from.
    HOME="$work/build-home" "$work/venv/bin/python" -m pip install --quiet "$artifact"

    (
        export HOME="$work/home"
        export PATH="$work/venv/bin:$PATH"
        cd "$work/run"

        version=$(sophios --version)
        echo "sophios --version: $version"
        if [ "$version" != "$expected" ]; then
            echo "ERROR: the install reports $version, the build resolved $expected"
            exit 1
        fi
        sophios --help > /dev/null
        python -c "import sophios, sophios.api.python.workflow, sophios.lang"
        sophios --explain wic016 | tee /dev/stderr | grep -q '^wic016 ('

        # The config, adapters and tutorials come from the installed package.
        sophios --generate_config
        sophios --yaml "$HOME/wic/examples/helloworld.wic" --generate_cwl_workflow
        test -s autogenerated/helloworld.cwl
        grep -q '^cwlVersion:' autogenerated/helloworld.cwl
        echo "compiled autogenerated/helloworld.cwl"
    )
    rm -rf "$work"
    echo "::endgroup::"
done
