"""Build a workflow in Python and turn it into a validated compute payload."""

from __future__ import annotations

from argparse import ArgumentParser
from datetime import datetime
import json
from pathlib import Path
import sys

from sophios.apis.python import (
    CommandLineTool,
    Input,
    Inputs,
    Output,
    Outputs,
    Workflow,
    cwl,
)
from sophios.compute_payload import ComputeWorkflowPayload
from sophios.compute_submit import submit_compute_payload


def build_emit_text_tool(python_executable: str | None = None) -> CommandLineTool:
    """Create a tiny CLT that writes a message to stdout.

    Args:
        python_executable (str | None): Optional Python interpreter override.

    Returns:
        CommandLineTool: A generated CWL CommandLineTool.
    """
    interpreter = python_executable or sys.executable
    inputs = Inputs(
        message=Input(cwl.string, position=1)
        .label("Message")
        .doc("Text to print to stdout."),
    )
    outputs = Outputs(
        text_file=Output(cwl.file, glob="stdout.txt")
        .label("Captured stdout")
        .doc("Text emitted by the tool, captured as a file."),
    )
    return (
        CommandLineTool("emit_text", inputs, outputs)
        .describe(
            "Emit text",
            "Small generated CLT that prints one message and captures stdout.",
        )
        .base_command(interpreter, "-c")
        .argument("import sys; print(sys.argv[1])", position=0)
        .stdout("stdout.txt")
    )


def build_workflow(message: str) -> Workflow:
    """Create a one-step workflow backed by an in-memory CLT.

    Args:
        message (str): Message that should flow into the generated tool.

    Returns:
        Workflow: A workflow that can compile entirely in memory.
    """
    emit_step = build_emit_text_tool().to_step(step_name="emit_text")
    workflow = Workflow([emit_step], "compute_payload_workflow_demo")
    emit_step.inputs.message = message
    workflow.add_output("text_file", emit_step.outputs.text_file)
    return workflow


def build_payload(message: str) -> ComputeWorkflowPayload:
    """Compile the workflow in memory and wrap it as a compute payload.

    Args:
        message (str): Message passed through the generated workflow input.

    Returns:
        ComputeWorkflowPayload: A validated compute payload object.
    """
    workflow = build_workflow(message)
    compiled_workflow = workflow.get_cwl_workflow()
    cwl_workflow = {
        key: value
        for key, value in compiled_workflow.items()
        if key not in {"name", "yaml_inputs"}
    }
    cwl_job_inputs = dict(compiled_workflow["yaml_inputs"])
    workflow_id = (
        f"{workflow.process_name}__{datetime.now().strftime('%Y_%m_%d_%H.%M.%S')}__"
    )
    return ComputeWorkflowPayload(
        cwl_workflow=cwl_workflow,
        cwl_job_inputs=cwl_job_inputs,
        workflow_id=workflow_id,
    )


def main() -> int:
    """Write or submit a compute payload built from Python workflow objects.

    Returns:
        int: Process exit status.
    """
    parser = ArgumentParser(description=__doc__)
    parser.add_argument(
        "--message",
        default="hello from compute payload workflow",
        help="Message passed through the generated workflow.",
    )
    parser.add_argument(
        "--validate-tool",
        action="store_true",
        help="Validate the generated CLT with cwltool/schema-salad first.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("autogenerated/compute_payload_workflow_demo.json"),
        help="Where to write the validated compute payload JSON.",
    )
    parser.add_argument(
        "--submit-url",
        help="Optional compute-slurm create-workflow endpoint. If provided, submit the payload.",
    )
    args = parser.parse_args()

    if args.validate_tool:
        build_emit_text_tool().validate()
        print("Validated generated CLT.")

    payload = build_payload(args.message)
    payload_json = payload.get_compute_payload()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(
        payload_json, indent=2), encoding="utf-8")
    print(f"Wrote {args.output}")

    if args.submit_url is None:
        return 0
    return submit_compute_payload(payload, args.submit_url)


if __name__ == "__main__":
    raise SystemExit(main())
