"""Build a workflow in Python and turn it into a validated compute request."""

from datetime import datetime
from pathlib import Path
import sys

from sophios.apis.python.tool_builder import (
    CommandLineTool,
    Input,
    Inputs,
    Output,
    Outputs,
    cwl,
)
from sophios.apis.python.workflow import (
    Step,
    Workflow,
)
from sophios.compute_request import ComputeRequest


MESSAGE = "hello from compute request workflow"
VALIDATE_TOOL = True
OUTPUT_PATH = Path("autogenerated/compute_request_workflow_demo.json")
SUBMIT_URL: str | None = None


def build_emit_text_tool(python_executable: str | None = None) -> CommandLineTool:
    """Create a compact CLT that writes a message to stdout.

    Args:
        python_executable (str | None): Optional Python interpreter override.

    Returns:
        CommandLineTool: A generated CWL CommandLineTool.
    """
    interpreter = python_executable or sys.executable
    inputs = Inputs(
        message=Input(cwl.string, position=1)
        .label("Message")
        .doc("Text to print to stdout."),
    )
    outputs = Outputs(
        text_file=Output(cwl.file, glob="stdout.txt")
        .label("Captured stdout")
        .doc("Text emitted by the tool, captured as a file."),
    )
    return (
        CommandLineTool("emit_text", inputs, outputs)
        .describe(
            "Emit text",
            "Small generated CLT that prints one message and captures stdout.",
        )
        .base_command(interpreter, "-c")
        .argument("import sys; print(sys.argv[1])", position=0)
        .stdout("stdout.txt")
    )


def build_workflow(message: str) -> Workflow:
    """Create a one-step workflow backed by an in-memory CLT.

    Args:
        message (str): Message that should flow into the generated tool.

    Returns:
        Workflow: A workflow that can compile entirely in memory.
    """
    emit_step = Step(build_emit_text_tool(), step_name="emit_text")
    workflow = Workflow([emit_step], "compute_request_workflow_demo")
    emit_step.inputs.message = message
    workflow.outputs.text_file = emit_step.outputs.text_file
    return workflow


def build_request(message: str) -> ComputeRequest:
    """Compile the workflow in memory and wrap it as a compute request.

    Args:
        message (str): Message passed through the generated workflow.

    Returns:
        ComputeRequest: A validated compute request object.
    """
    workflow = build_workflow(message)
    compiled_workflow = workflow.compile()
    workflow_id = (
        f"{workflow.process_name}__{datetime.now().strftime('%Y_%m_%d_%H.%M.%S')}__"
    )
    return ComputeRequest.from_compiled(
        compiled_workflow,
        workflow_id=workflow_id,
    )


def main() -> int:
    """Write or submit a compute request built from Python workflow objects.

    Returns:
        int: Process exit status.
    """
    if VALIDATE_TOOL:
        build_emit_text_tool().validate()
        print("Validated generated CLT.")

    request = build_request(MESSAGE)
    request_json = request.to_json(indent=2)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(request_json, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")

    if SUBMIT_URL is None:
        return 0
    return request.submit(SUBMIT_URL).exit_code


if __name__ == "__main__":
    raise SystemExit(main())
