"""Run a multistep Sophios workflow with an explicitly configured CWL runner."""

from pathlib import Path

from sophios.apis.python.workflow import Step, Workflow


REPO_ROOT = Path(__file__).resolve().parents[2]
ADAPTERS = REPO_ROOT / "cwl_adapters"
BASEPATH = "autogenerated/multistep_runner_pyapi"

# Sophios supports "cwltool" and "toil-cwl-runner" for local Workflow.run().
# This example uses cwltool. To run with Toil, change cwl_runner to
# "toil-cwl-runner" and add Toil options such as "logLevel": "INFO".
RUN_ARGS = {
    "cwl_runner": "cwltool",
    "container_engine": "docker",
    "copy_output_files": "yes",
}


def workflow() -> Workflow:
    """Build a three-step workflow that creates, appends, and reads a file."""
    touch = Step(clt_path=ADAPTERS / "touch.cwl")
    touch.inputs.filename = "empty.txt"

    append = Step(clt_path=ADAPTERS / "append.cwl")
    append.inputs.file = touch.outputs.file
    append.inputs.str = "Hello"

    cat = Step(clt_path=ADAPTERS / "cat.cwl")
    cat.inputs.file = append.outputs.file

    workflow_ = Workflow([touch, append, cat], "multistep_runner_pyapi")
    workflow_.outputs.result = cat.outputs.output
    return workflow_


if __name__ == "__main__":
    workflow().run(run_args_dict=RUN_ARGS, basepath=BASEPATH)
