"""Build and compose in-memory CWL tools with the Sophios workflow Python API."""

from pathlib import Path
import sys

from sophios.apis.python.tool_builder import (
    CommandLineTool,
    Input,
    Inputs,
    Output,
    Outputs,
    cwl,
)
from sophios.apis.python.workflow import (
    Step,
    Workflow,
)


MESSAGE = "hello from tool_builder"
VALIDATE_TOOLS = True
RUN_WORKFLOW = False
BASEPATH = "autogenerated"
WRITE_TOOLS_DIR: Path | None = None


def build_emit_text_tool(python_executable: str | None = None) -> CommandLineTool:
    """Create a compact CLT that writes a message to stdout."""
    interpreter = python_executable or sys.executable
    inputs = Inputs(
        message=Input(cwl.string, position=1)
        .label("Message")
        .doc("Text to print to stdout."),
    )
    outputs = Outputs(
        text_file=Output(cwl.file, glob="stdout.txt")
        .label("Captured stdout")
        .doc("Text emitted by the tool, captured as a file."),
    )
    return (
        CommandLineTool("emit_text", inputs, outputs)
        .describe(
            "Emit text",
            "Small generated CLT that prints one message and captures stdout.",
        )
        .base_command(interpreter, "-c")
        .argument("import sys; print(sys.argv[1])", position=0)
        .stdout("stdout.txt")
    )


def build_read_text_tool(python_executable: str | None = None) -> CommandLineTool:
    """Create a CLT that reads a text file and returns its contents as a string."""
    interpreter = python_executable or sys.executable
    inputs = Inputs(
        text_file=Input(cwl.file, position=1)
        .label("Text file")
        .doc("Input file whose contents should be returned."),
    )
    outputs = Outputs(
        result=Output(
            cwl.string,
            glob="stdout.txt",
            load_contents=True,
            output_eval="$(self[0].contents)",
        )
        .label("Result text")
        .doc("String value loaded from the generated stdout file."),
    )
    return (
        CommandLineTool("read_text_file", inputs, outputs)
        .describe(
            "Read text",
            "Generated CLT that loads a file and prints its text content.",
        )
        .base_command(interpreter, "-c")
        .argument(
            (
                "from pathlib import Path; import sys; "
                "print(Path(sys.argv[1]).read_text(encoding='utf-8').strip())"
            ),
            position=0,
        )
        .stdout("stdout.txt")
    )


def build_workflow(message: str = "hello from tool_builder") -> Workflow:
    """Create a workflow that chains two generated CLTs entirely in memory."""
    emit_step = Step(build_emit_text_tool(), step_name="emit_text")
    read_step = Step(build_read_text_tool(), step_name="read_text")

    emit_step.inputs.message = message
    read_step.inputs.text_file = emit_step.outputs.text_file

    workflow = Workflow([emit_step, read_step], "tool_builder_workflow_demo")
    workflow.outputs.result = read_step.outputs.result
    return workflow


def main() -> int:
    """Compile or run the builder-plus-workflow demo."""
    emit_tool = build_emit_text_tool()
    read_tool = build_read_text_tool()

    if VALIDATE_TOOLS:
        emit_tool.validate()
        read_tool.validate()
        print("Validated generated CLTs.")

    if WRITE_TOOLS_DIR is not None:
        WRITE_TOOLS_DIR.mkdir(parents=True, exist_ok=True)
        emit_path = emit_tool.write_cwl(WRITE_TOOLS_DIR / "emit_text.cwl")
        read_path = read_tool.write_cwl(WRITE_TOOLS_DIR / "read_text_file.cwl")
        print(f"Wrote {emit_path}")
        print(f"Wrote {read_path}")

    workflow = build_workflow(message=MESSAGE)

    if not RUN_WORKFLOW:
        compiled = workflow.compile()
        compiled.write_cwl(BASEPATH)
        compiled.write_job_inputs(BASEPATH)
        print(f"Compiled workflow {workflow.process_name} to autogenerated/")
        return 0

    workflow.run(basepath=BASEPATH)
    print(f"Ran workflow {workflow.process_name}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
